import { RoleStatus } from '../schemas/role.schema';

export interface SeedRoleDefinition {
  name: string;
  key: string;
  description: string;
  isSystem: boolean;
  status: RoleStatus;
  permissions: string[];
}

export const SEED_ROLES: SeedRoleDefinition[] = [
  {
    name: 'Super Admin',
    key: 'super_admin',
    description: 'Root platform authority with unrestricted access across all present and future administrative capabilities.',
    isSystem: true,
    status: RoleStatus.ACTIVE,
    permissions: ['*'],
  },
  {
    name: 'Administrator',
    key: 'admin',
    description: 'Supervises operations, staff invitations, catalog, orders, and customer dispute resolution.',
    isSystem: true,
    status: RoleStatus.ACTIVE,
    // Everything except settings.edit and audit_logs.export
    permissions: [
      'dashboard.view',
      'users.view',
      'users.invite',
      'users.edit',
      'users.activate',
      'users.delete',
      'roles.view',
      'roles.create',
      'roles.edit',
      'roles.delete',
      'roles.assign',
      'audit_logs.view',
      'products.view',
      'products.create',
      'products.edit',
      'products.delete',
      'products.publish',
      'products.import',
      'products.export',
      'categories.view',
      'categories.create',
      'categories.edit',
      'categories.delete',
      'brands.view',
      'brands.create',
      'brands.edit',
      'brands.delete',
      'inventory.view',
      'inventory.adjust',
      'inventory.export',
      'orders.view',
      'orders.edit',
      'orders.cancel',
      'orders.refund',
      'orders.export',
      'returns.view',
      'returns.approve',
      'payments.view',
      'customers.view',
      'customers.edit',
      'customers.activate',
      'customers.export',
      'reviews.view',
      'reviews.approve',
      'reviews.delete',
      'coupons.view',
      'coupons.create',
      'coupons.edit',
      'coupons.delete',
      'reports.view',
      'reports.export',
      'settings.view',
    ],
  },
  {
    name: 'Operations Manager',
    key: 'operations_manager',
    description: 'Manages orders, returns, inventory stock, customer data, and operational reporting.',
    isSystem: false,
    status: RoleStatus.ACTIVE,
    permissions: [
      'dashboard.view',
      'products.view',
      'inventory.view',
      'inventory.adjust',
      'orders.view',
      'orders.edit',
      'orders.cancel',
      'orders.export',
      'returns.view',
      'returns.approve',
      'customers.view',
      'reports.view',
      'reports.export',
    ],
  },
  {
    name: 'Catalog Manager',
    key: 'catalog_manager',
    description: 'Responsible for product catalog creation, categories, brand partnerships, and stock checks.',
    isSystem: false,
    status: RoleStatus.ACTIVE,
    permissions: [
      'dashboard.view',
      'products.view',
      'products.create',
      'products.edit',
      'products.delete',
      'products.publish',
      'products.import',
      'products.export',
      'categories.view',
      'categories.create',
      'categories.edit',
      'categories.delete',
      'brands.view',
      'brands.create',
      'brands.edit',
      'brands.delete',
      'inventory.view',
      'inventory.adjust',
      'inventory.export',
    ],
  },
  {
    name: 'Order Manager',
    key: 'order_manager',
    description: 'Processes sales orders, status updates, cancellations, and order exports.',
    isSystem: false,
    status: RoleStatus.ACTIVE,
    permissions: [
      'dashboard.view',
      'products.view',
      'inventory.view',
      'orders.view',
      'orders.edit',
      'orders.cancel',
      'orders.export',
      'returns.view',
      'customers.view',
    ],
  },
  {
    name: 'Customer Support',
    key: 'customer_support',
    description: 'Resolves customer inquiries, inspects order histories, and moderates reviews.',
    isSystem: false,
    status: RoleStatus.ACTIVE,
    permissions: [
      'dashboard.view',
      'products.view',
      'orders.view',
      'returns.view',
      'customers.view',
      'customers.edit',
      'customers.activate',
      'reviews.view',
      'reviews.approve',
      'reviews.delete',
    ],
  },
  {
    name: 'Marketing Manager',
    key: 'marketing_manager',
    description: 'Creates coupons, promotional campaigns, analyzes reviews, and monitors sales velocity.',
    isSystem: false,
    status: RoleStatus.ACTIVE,
    permissions: [
      'dashboard.view',
      'products.view',
      'customers.view',
      'reviews.view',
      'coupons.view',
      'coupons.create',
      'coupons.edit',
      'coupons.delete',
      'reports.view',
    ],
  },
  {
    name: 'Finance Manager',
    key: 'finance_manager',
    description: 'Oversees customer refunds, payment reconciliation, returns, and financial reports.',
    isSystem: false,
    status: RoleStatus.ACTIVE,
    permissions: [
      'dashboard.view',
      'orders.view',
      'orders.refund',
      'orders.export',
      'returns.view',
      'returns.approve',
      'payments.view',
      'customers.view',
      'reports.view',
      'reports.export',
    ],
  },
  {
    name: 'Warehouse Manager',
    key: 'warehouse_manager',
    description: 'Manages physical warehouse inventory adjustments, order fulfillment status, and stock checks.',
    isSystem: false,
    status: RoleStatus.ACTIVE,
    permissions: [
      'dashboard.view',
      'products.view',
      'inventory.view',
      'inventory.adjust',
      'orders.view',
      'orders.edit',
    ],
  },
];
