/**
 * Machine-readable error codes returned in the error envelope's `code` field,
 * so clients can branch on the failure type instead of parsing messages.
 */
export enum ErrorCode {
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  ACCOUNT_DISABLED = 'ACCOUNT_DISABLED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  WRONG_PORTAL = 'WRONG_PORTAL',
  EMAIL_TAKEN = 'EMAIL_TAKEN',
  INVALID_TOKEN = 'INVALID_TOKEN',
  EMAIL_ALREADY_VERIFIED = 'EMAIL_ALREADY_VERIFIED',
  PASSWORD_CHANGE_REQUIRED = 'PASSWORD_CHANGE_REQUIRED',
  PASSWORD_REUSED = 'PASSWORD_REUSED',
  PASSWORD_INCORRECT = 'PASSWORD_INCORRECT',
  PASSWORD_NOT_SET = 'PASSWORD_NOT_SET',
  MFA_CHALLENGE_INVALID = 'MFA_CHALLENGE_INVALID',
  MFA_INVALID_CODE = 'MFA_INVALID_CODE',
  MFA_ALREADY_ENABLED = 'MFA_ALREADY_ENABLED',
  MFA_NOT_ENABLED = 'MFA_NOT_ENABLED',
  MFA_SETUP_NOT_STARTED = 'MFA_SETUP_NOT_STARTED',
  OAUTH_PROVIDER_DISABLED = 'OAUTH_PROVIDER_DISABLED',
  OAUTH_FAILED = 'OAUTH_FAILED',
  OAUTH_STAFF_NOT_ALLOWED = 'OAUTH_STAFF_NOT_ALLOWED',
  OAUTH_EMAIL_UNVERIFIED = 'OAUTH_EMAIL_UNVERIFIED',
  INVITATION_EXPIRED = 'INVITATION_EXPIRED',
  INVITATION_REVOKED = 'INVITATION_REVOKED',
}
