export enum WarehouseType {
  PRIMARY_DISTRIBUTION = 'PRIMARY_DISTRIBUTION',
  REGIONAL_HUB = 'REGIONAL_HUB',
  LOCAL_STORE = 'LOCAL_STORE',
  RETURN_CENTER = 'RETURN_CENTER',
}

export enum WarehouseStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  MAINTENANCE = 'MAINTENANCE',
}

export enum TransferStatus {
  DRAFT = 'DRAFT',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  IN_TRANSIT = 'IN_TRANSIT',
  PARTIALLY_RECEIVED = 'PARTIALLY_RECEIVED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
