import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { Category, CategoryDocument } from './schemas/category.schema';
import { CategoriesService } from './categories.service';

interface CategorySeedDef {
  name: string;
  slug: string;
  description: string;
  displayOrder: number;
  iconUrl: string;
  thumbnailUrl: string;
  bannerDesktopUrl: string;
  bannerMobileUrl: string;
  imageAltText: string;
  includeInMenu: boolean;
  isFeatured: boolean;
  badge: { text: string; color: 'indigo' | 'emerald' | 'amber' | 'rose' } | null;
  filterableAttributes: string[];
  seo: {
    metaTitle: string;
    metaDescription: string;
    keywords: string[];
    canonicalUrl: string;
    ogImage: string;
  };
  children?: (Omit<CategorySeedDef, 'children'> & {
    children?: Omit<CategorySeedDef, 'children'>[];
  })[];
}

export const SEED_CATEGORIES: CategorySeedDef[] = [
  {
    name: 'Electronics & Computing',
    slug: 'electronics-computing',
    description: 'Cutting-edge digital devices, high performance computers, and smart personal electronics.',
    displayOrder: 1,
    iconUrl: 'https://api.iconify.design/lucide:laptop.svg?color=%234f46e5',
    thumbnailUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=600&auto=format&fit=crop&q=80',
    bannerDesktopUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1920&auto=format&fit=crop&q=80',
    bannerMobileUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80',
    imageAltText: 'Modern electronics workstation showcasing ultrabooks and gadgets',
    includeInMenu: true,
    isFeatured: true,
    badge: { text: 'POPULAR', color: 'indigo' },
    filterableAttributes: ['brand', 'processor', 'ram', 'storage', 'warranty'],
    seo: {
      metaTitle: 'Electronics & Computing Gear | Best Deals Online | ZYLO',
      metaDescription: 'Shop premier electronics, computing workstations, laptops, and mobile accessories with fast global delivery.',
      keywords: ['electronics', 'computers', 'tech gadgets', 'zylo electronics'],
      canonicalUrl: 'https://zylo.com/categories/electronics-computing',
      ogImage: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200&auto=format&fit=crop&q=80',
    },
    children: [
      {
        name: 'Laptops & Notebooks',
        slug: 'laptops-notebooks',
        description: 'Ultraportable laptops, high-performance creator workstations, and business notebooks.',
        displayOrder: 1,
        iconUrl: 'https://api.iconify.design/lucide:laptop-2.svg?color=%234f46e5',
        thumbnailUrl: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&auto=format&fit=crop&q=80',
        bannerDesktopUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=1920&auto=format&fit=crop&q=80',
        bannerMobileUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
        imageAltText: 'Minimalist aluminum laptop on designer oak work desk',
        includeInMenu: true,
        isFeatured: true,
        badge: { text: 'HOT', color: 'amber' },
        filterableAttributes: ['brand', 'screen_size', 'ram', 'processor', 'storage', 'gpu'],
        seo: {
          metaTitle: 'Buy Ultrabooks & High Performance Laptops | ZYLO',
          metaDescription: 'Discover slim ultrabooks and pro creator notebooks engineered for peak multitasking speed.',
          keywords: ['laptops', 'ultrabooks', 'creator notebooks'],
          canonicalUrl: 'https://zylo.com/categories/laptops-notebooks',
          ogImage: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=1200&auto=format&fit=crop&q=80',
        },
        children: [
          {
            name: 'Gaming Laptops',
            slug: 'gaming-laptops',
            description: 'Extreme refresh rate displays, dedicated RTX graphics, and advanced thermal cooling.',
            displayOrder: 1,
            iconUrl: 'https://api.iconify.design/lucide:gamepad-2.svg?color=%234f46e5',
            thumbnailUrl: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600&auto=format&fit=crop&q=80',
            bannerDesktopUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1920&auto=format&fit=crop&q=80',
            bannerMobileUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80',
            imageAltText: 'High performance RGB illuminated esports gaming laptop',
            includeInMenu: true,
            isFeatured: false,
            badge: { text: '240HZ', color: 'rose' },
            filterableAttributes: ['brand', 'gpu', 'refresh_rate', 'ram', 'cpu'],
            seo: {
              metaTitle: 'Esports & Gaming Laptops with RTX Graphics | ZYLO',
              metaDescription: 'Level up your gaming experience with powerful RTX graphics and lightning 240Hz screens.',
              keywords: ['gaming laptops', 'rtx laptops', 'esports rig'],
              canonicalUrl: 'https://zylo.com/categories/gaming-laptops',
              ogImage: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=1200&auto=format&fit=crop&q=80',
            },
          },
        ],
      },
      {
        name: 'Smartphones & Foldables',
        slug: 'smartphones-foldables',
        description: 'Next-gen flagship smartphones, AI photography powerhouses, and foldable OLED devices.',
        displayOrder: 2,
        iconUrl: 'https://api.iconify.design/lucide:smartphone.svg?color=%234f46e5',
        thumbnailUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02547?w=600&auto=format&fit=crop&q=80',
        bannerDesktopUrl: 'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=1920&auto=format&fit=crop&q=80',
        bannerMobileUrl: 'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=800&auto=format&fit=crop&q=80',
        imageAltText: 'Sleek premium 5G smartphone with bezel-less glass display',
        includeInMenu: true,
        isFeatured: true,
        badge: { text: 'NEW', color: 'emerald' },
        filterableAttributes: ['brand', 'os', 'storage', 'camera_mp', 'color', 'battery_mah'],
        seo: {
          metaTitle: 'Flagship 5G Smartphones & Foldable OLED Phones | ZYLO',
          metaDescription: 'Shop cutting edge mobile phones with pro grade cameras and all day battery performance.',
          keywords: ['smartphones', 'foldable phones', '5g mobile'],
          canonicalUrl: 'https://zylo.com/categories/smartphones-foldables',
          ogImage: 'https://images.unsplash.com/photo-1511707171634-5f897ff02547?w=1200&auto=format&fit=crop&q=80',
        },
      },
    ],
  },
  {
    name: 'Fashion & Apparel',
    slug: 'fashion-apparel',
    description: 'Curated international designer wear, contemporary streetwear, and timeless luxury wardrobe essentials.',
    displayOrder: 2,
    iconUrl: 'https://api.iconify.design/lucide:shirt.svg?color=%234f46e5',
    thumbnailUrl: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=600&auto=format&fit=crop&q=80',
    bannerDesktopUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1920&auto=format&fit=crop&q=80',
    bannerMobileUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&auto=format&fit=crop&q=80',
    imageAltText: 'Sophisticated minimalist fashion apparel hanging on clean retail rack',
    includeInMenu: true,
    isFeatured: true,
    badge: { text: 'LUXURY', color: 'rose' },
    filterableAttributes: ['brand', 'gender', 'size', 'color', 'material', 'season'],
    seo: {
      metaTitle: 'Designer Fashion & Modern Apparel Collection | ZYLO',
      metaDescription: 'Explore runway styles, everyday essentials, and luxury silhouettes handcrafted with premium fabrics.',
      keywords: ['fashion', 'designer apparel', 'luxury clothing'],
      canonicalUrl: 'https://zylo.com/categories/fashion-apparel',
      ogImage: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=1200&auto=format&fit=crop&q=80',
    },
    children: [
      {
        name: "Men's Designer Wear",
        slug: 'mens-designer-wear',
        description: 'Tailored suits, premium cotton shirts, structured jackets, and casual luxury menswear.',
        displayOrder: 1,
        iconUrl: 'https://api.iconify.design/lucide:user.svg?color=%234f46e5',
        thumbnailUrl: 'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?w=600&auto=format&fit=crop&q=80',
        bannerDesktopUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=1920&auto=format&fit=crop&q=80',
        bannerMobileUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80',
        imageAltText: 'Sharply tailored bespoke mens formal blazer and pocket square',
        includeInMenu: true,
        isFeatured: false,
        badge: { text: 'TRENDING', color: 'amber' },
        filterableAttributes: ['brand', 'size', 'fit', 'fabric', 'color', 'pattern'],
        seo: {
          metaTitle: "Men's Tailored Clothing & Designer Menswear | ZYLO",
          metaDescription: 'Elevate your personal aesthetic with bespoke suits and modern casual menswear.',
          keywords: ['menswear', 'mens suits', 'designer shirts'],
          canonicalUrl: 'https://zylo.com/categories/mens-designer-wear',
          ogImage: 'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?w=1200&auto=format&fit=crop&q=80',
        },
      },
      {
        name: "Women's Luxury Collection",
        slug: 'womens-luxury-collection',
        description: 'Haute couture evening wear, silk blouses, structured blazers, and statement accessories.',
        displayOrder: 2,
        iconUrl: 'https://api.iconify.design/lucide:sparkle.svg?color=%234f46e5',
        thumbnailUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=600&auto=format&fit=crop&q=80',
        bannerDesktopUrl: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=1920&auto=format&fit=crop&q=80',
        bannerMobileUrl: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=800&auto=format&fit=crop&q=80',
        imageAltText: 'Modern woman in high fashion designer coat holding luxury handbag',
        includeInMenu: true,
        isFeatured: true,
        badge: { text: 'EXCLUSIVE', color: 'emerald' },
        filterableAttributes: ['brand', 'dress_size', 'color', 'fabric', 'occasion'],
        seo: {
          metaTitle: "Women's Haute Couture & Designer Wardrobe | ZYLO",
          metaDescription: 'Shop elegant silhouettes, silk evening dresses, and designer coats designed for timeless elegance.',
          keywords: ['womens fashion', 'luxury dresses', 'designer womenswear'],
          canonicalUrl: 'https://zylo.com/categories/womens-luxury-collection',
          ogImage: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=1200&auto=format&fit=crop&q=80',
        },
      },
    ],
  },
  {
    name: 'Home & Living',
    slug: 'home-living',
    description: 'Scandinavian minimalist furniture, ambient smart illumination, and artisanal home accents.',
    displayOrder: 3,
    iconUrl: 'https://api.iconify.design/lucide:armchair.svg?color=%234f46e5',
    thumbnailUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80',
    bannerDesktopUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1920&auto=format&fit=crop&q=80',
    bannerMobileUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&auto=format&fit=crop&q=80',
    imageAltText: 'Bright scandinavian living room featuring minimalist furniture and natural light',
    includeInMenu: true,
    isFeatured: true,
    badge: null,
    filterableAttributes: ['brand', 'room', 'material', 'color', 'style'],
    seo: {
      metaTitle: 'Modern Home Decor & Minimalist Living Furniture | ZYLO',
      metaDescription: 'Transform your space with curated architectural furniture and calming ambient decor.',
      keywords: ['home decor', 'modern furniture', 'scandinavian interior'],
      canonicalUrl: 'https://zylo.com/categories/home-living',
      ogImage: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1200&auto=format&fit=crop&q=80',
    },
    children: [
      {
        name: 'Modern Furniture',
        slug: 'modern-furniture',
        description: 'Architectural lounge chairs, solid oak dining tables, ergonomic desks, and modular sectionals.',
        displayOrder: 1,
        iconUrl: 'https://api.iconify.design/lucide:sofa.svg?color=%234f46e5',
        thumbnailUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&auto=format&fit=crop&q=80',
        bannerDesktopUrl: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=1920&auto=format&fit=crop&q=80',
        bannerMobileUrl: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&auto=format&fit=crop&q=80',
        imageAltText: 'Plush emerald velvet mid-century sofa with brass accent legs',
        includeInMenu: true,
        isFeatured: false,
        badge: { text: 'HANDMADE', color: 'indigo' },
        filterableAttributes: ['brand', 'material', 'finish', 'dimensions', 'color'],
        seo: {
          metaTitle: 'Architectural Modern Furniture & Sofas | ZYLO',
          metaDescription: 'Bespoke solid wood tables, cozy sectionals, and iconic lounge seating crafted for comfort.',
          keywords: ['sofas', 'chairs', 'tables', 'wood furniture'],
          canonicalUrl: 'https://zylo.com/categories/modern-furniture',
          ogImage: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=1200&auto=format&fit=crop&q=80',
        },
      },
      {
        name: 'Smart Home Lighting',
        slug: 'smart-home-lighting',
        description: 'Circadian rhythm smart bulbs, architectural pendant fixtures, and voice-controlled LED strips.',
        displayOrder: 2,
        iconUrl: 'https://api.iconify.design/lucide:lightbulb.svg?color=%234f46e5',
        thumbnailUrl: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&auto=format&fit=crop&q=80',
        bannerDesktopUrl: 'https://images.unsplash.com/photo-1565814636199-ae8133055c1c?w=1920&auto=format&fit=crop&q=80',
        bannerMobileUrl: 'https://images.unsplash.com/photo-1565814636199-ae8133055c1c?w=800&auto=format&fit=crop&q=80',
        imageAltText: 'Warm filament Edison bulb glowing softly in modern industrial pendant',
        includeInMenu: true,
        isFeatured: false,
        badge: { text: 'SMART', color: 'emerald' },
        filterableAttributes: ['brand', 'connectivity', 'color_temp', 'wattage', 'lumens'],
        seo: {
          metaTitle: 'Smart Home Lighting & Architectural Lamps | ZYLO',
          metaDescription: 'Illuminate your rooms with tunable white and 16-million color connected lighting solutions.',
          keywords: ['smart bulbs', 'ambient lighting', 'pendant lamps'],
          canonicalUrl: 'https://zylo.com/categories/smart-home-lighting',
          ogImage: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=1200&auto=format&fit=crop&q=80',
        },
      },
    ],
  },
  {
    name: 'Audio & Sound Systems',
    slug: 'audio-sound-systems',
    description: 'Audiophile grade studio equipment, true wireless earbuds, soundbars, and vinyl turntables.',
    displayOrder: 4,
    iconUrl: 'https://api.iconify.design/lucide:headphones.svg?color=%234f46e5',
    thumbnailUrl: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&auto=format&fit=crop&q=80',
    bannerDesktopUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1920&auto=format&fit=crop&q=80',
    bannerMobileUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80',
    imageAltText: 'Matte black premium over-ear headphones resting on acoustic wood block',
    includeInMenu: true,
    isFeatured: true,
    badge: { text: 'HI-RES', color: 'amber' },
    filterableAttributes: ['brand', 'wireless', 'battery_life', 'anc', 'frequency_response'],
    seo: {
      metaTitle: 'Audiophile Grade Sound Systems & Headphones | ZYLO',
      metaDescription: 'Immerse yourself in rich acoustic resolution with studio reference monitors and wireless ANC headphones.',
      keywords: ['headphones', 'sound systems', 'hi-fi audio'],
      canonicalUrl: 'https://zylo.com/categories/audio-sound-systems',
      ogImage: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=1200&auto=format&fit=crop&q=80',
    },
    children: [
      {
        name: 'Wireless Noise-Canceling Headphones',
        slug: 'wireless-noise-canceling-headphones',
        description: 'Active hybrid noise cancellation, spatial audio tracking, and 40-hour battery life.',
        displayOrder: 1,
        iconUrl: 'https://api.iconify.design/lucide:headset.svg?color=%234f46e5',
        thumbnailUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
        bannerDesktopUrl: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=1920&auto=format&fit=crop&q=80',
        bannerMobileUrl: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&auto=format&fit=crop&q=80',
        imageAltText: 'Close up of gold accented luxury wireless headphones with leather earcups',
        includeInMenu: true,
        isFeatured: true,
        badge: { text: 'BESTSELLER', color: 'emerald' },
        filterableAttributes: ['brand', 'anc_type', 'bluetooth_version', 'driver_size', 'color'],
        seo: {
          metaTitle: 'Best Wireless Active Noise-Canceling Headphones | ZYLO',
          metaDescription: 'Block out ambient distractions and enjoy studio fidelity on your daily commute or flights.',
          keywords: ['anc headphones', 'bluetooth headphones', 'noise canceling'],
          canonicalUrl: 'https://zylo.com/categories/wireless-noise-canceling-headphones',
          ogImage: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1200&auto=format&fit=crop&q=80',
        },
      },
      {
        name: 'Studio Monitors & Hi-Fi Speakers',
        slug: 'studio-monitors-hifi-speakers',
        description: 'Bi-amplified nearfield monitors, wooden bookshelf speakers, and high power living room soundbars.',
        displayOrder: 2,
        iconUrl: 'https://api.iconify.design/lucide:volume-2.svg?color=%234f46e5',
        thumbnailUrl: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&auto=format&fit=crop&q=80',
        bannerDesktopUrl: 'https://images.unsplash.com/photo-1519500099198-fd81846b8f03?w=1920&auto=format&fit=crop&q=80',
        bannerMobileUrl: 'https://images.unsplash.com/photo-1519500099198-fd81846b8f03?w=800&auto=format&fit=crop&q=80',
        imageAltText: 'Pair of precision wood enclosure studio monitor speakers on stands',
        includeInMenu: true,
        isFeatured: false,
        badge: { text: 'STUDIO', color: 'indigo' },
        filterableAttributes: ['brand', 'power_watts', 'inputs', 'woofer_size', 'impedance'],
        seo: {
          metaTitle: 'Professional Studio Monitors & Hi-Fi Bookshelf Speakers | ZYLO',
          metaDescription: 'Experience pristine frequency response with reference monitors for music producers and sound purists.',
          keywords: ['studio monitors', 'speakers', 'hifi audio'],
          canonicalUrl: 'https://zylo.com/categories/studio-monitors-hifi-speakers',
          ogImage: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=1200&auto=format&fit=crop&q=80',
        },
      },
    ],
  },
  {
    name: 'Beauty & Skincare',
    slug: 'beauty-skincare',
    description: 'Clean organic cosmetics, anti-aging peptide serums, dermatological treatments, and luxury scents.',
    displayOrder: 5,
    iconUrl: 'https://api.iconify.design/lucide:sparkles.svg?color=%234f46e5',
    thumbnailUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&auto=format&fit=crop&q=80',
    bannerDesktopUrl: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=1920&auto=format&fit=crop&q=80',
    bannerMobileUrl: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&auto=format&fit=crop&q=80',
    imageAltText: 'Artistic composition of luxury skincare glass dropper bottles and cream jars',
    includeInMenu: true,
    isFeatured: true,
    badge: { text: 'ORGANIC', color: 'emerald' },
    filterableAttributes: ['brand', 'skin_type', 'concern', 'ingredients', 'cruelty_free'],
    seo: {
      metaTitle: 'Clean Organic Skincare & Luxury Beauty Essentials | ZYLO',
      metaDescription: 'Nourish your skin with clinically proven clean formulations free from parabens and sulfates.',
      keywords: ['skincare', 'clean beauty', 'organic cosmetics'],
      canonicalUrl: 'https://zylo.com/categories/beauty-skincare',
      ogImage: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=1200&auto=format&fit=crop&q=80',
    },
    children: [
      {
        name: 'Organic Facial Care',
        slug: 'organic-facial-care',
        description: 'Hyaluronic acid hydration serums, restorative retinol night creams, and soothing botanical toners.',
        displayOrder: 1,
        iconUrl: 'https://api.iconify.design/lucide:droplet.svg?color=%234f46e5',
        thumbnailUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80',
        bannerDesktopUrl: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=1920&auto=format&fit=crop&q=80',
        bannerMobileUrl: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&auto=format&fit=crop&q=80',
        imageAltText: 'Pipette applying pure organic botanical serum drop on crystal glass surface',
        includeInMenu: true,
        isFeatured: false,
        badge: { text: 'VEGAN', color: 'emerald' },
        filterableAttributes: ['brand', 'skin_type', 'spf', 'volume_ml', 'formulation'],
        seo: {
          metaTitle: 'Natural Facial Serums, Moisturisers & Toners | ZYLO',
          metaDescription: 'Target fine lines, redness, and dehydration with pure cold-pressed organic facial treatments.',
          keywords: ['facial serums', 'face creams', 'organic toner'],
          canonicalUrl: 'https://zylo.com/categories/organic-facial-care',
          ogImage: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=1200&auto=format&fit=crop&q=80',
        },
      },
      {
        name: 'Artisan Fragrances',
        slug: 'artisan-fragrances',
        description: 'Small-batch eau de parfum, rare oud extraits, smoky cedar notes, and delicate floral bouquets.',
        displayOrder: 2,
        iconUrl: 'https://api.iconify.design/lucide:flame.svg?color=%234f46e5',
        thumbnailUrl: 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?w=600&auto=format&fit=crop&q=80',
        bannerDesktopUrl: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=1920&auto=format&fit=crop&q=80',
        bannerMobileUrl: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800&auto=format&fit=crop&q=80',
        imageAltText: 'Amber glass perfume bottle reflecting dramatic studio lighting',
        includeInMenu: true,
        isFeatured: true,
        badge: { text: 'PARFUM', color: 'rose' },
        filterableAttributes: ['brand', 'scent_family', 'concentration', 'size_ml', 'gender'],
        seo: {
          metaTitle: 'Bespoke Artisan Fragrances & Eau de Parfum | ZYLO',
          metaDescription: 'Discover niche fragrance houses and master perfumers blending rare woods and florals.',
          keywords: ['perfumes', 'artisan fragrances', 'eau de parfum'],
          canonicalUrl: 'https://zylo.com/categories/artisan-fragrances',
          ogImage: 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?w=1200&auto=format&fit=crop&q=80',
        },
      },
    ],
  },
  {
    name: 'Sports, Fitness & Outdoor Adventure',
    slug: 'sports-fitness-outdoors',
    description: 'High-performance athletic gear, pro workout apparatus, and rugged all-weather outdoor expedition apparel.',
    displayOrder: 5,
    iconUrl: 'https://api.iconify.design/lucide:dumbbell.svg?color=%234f46e5',
    thumbnailUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80',
    bannerDesktopUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1920&auto=format&fit=crop&q=80',
    bannerMobileUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
    imageAltText: 'Modern commercial grade fitness training room with weights and workout stations',
    includeInMenu: true,
    isFeatured: true,
    badge: { text: 'FITNESS', color: 'indigo' },
    filterableAttributes: ['brand', 'sport_type', 'intensity_level', 'weight_capacity', 'warranty'],
    seo: {
      metaTitle: 'Sports, Fitness & Outdoor Gear | ZYLO Athletics',
      metaDescription: 'Shop high-performance gym equipment, athletic activewear, and expedition hiking essentials.',
      keywords: ['fitness gear', 'workout equipment', 'outdoor apparel', 'zylo fitness'],
      canonicalUrl: 'https://zylo.com/categories/sports-fitness-outdoors',
      ogImage: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=1200&auto=format&fit=crop&q=80',
    },
    children: [
      {
        name: 'Cardio & Strength Equipment',
        slug: 'cardio-strength-equipment',
        description: 'Commercial power racks, Olympic bar sets, intelligent magnetic resistance bikes, and treadmills.',
        displayOrder: 1,
        iconUrl: 'https://api.iconify.design/lucide:activity.svg?color=%234f46e5',
        thumbnailUrl: 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&auto=format&fit=crop&q=80',
        bannerDesktopUrl: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=1920&auto=format&fit=crop&q=80',
        bannerMobileUrl: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop&q=80',
        imageAltText: 'High performance barbell racks and adjustable resistance machines in professional fitness club',
        includeInMenu: true,
        isFeatured: true,
        badge: { text: 'HEAVY-DUTY', color: 'amber' },
        filterableAttributes: ['brand', 'weight_stack_kg', 'resistance_type', 'foldable', 'warranty_years'],
        seo: {
          metaTitle: 'Cardio & Strength Training Equipment | Pro Home Gym | ZYLO',
          metaDescription: 'Build your dream home gym with commercial grade treadmills, power cages, and Olympic bumper plates.',
          keywords: ['strength equipment', 'home gym', 'cardio machines', 'dumbbells'],
          canonicalUrl: 'https://zylo.com/categories/cardio-strength-equipment',
          ogImage: 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=1200&auto=format&fit=crop&q=80',
        },
        children: [
          {
            name: 'Smart Connected Home Gyms',
            slug: 'smart-connected-fitness',
            description: 'AI-guided digital weight trainers, touch-screen fitness mirrors, and live coaching workout hubs.',
            displayOrder: 1,
            iconUrl: 'https://api.iconify.design/lucide:cpu.svg?color=%234f46e5',
            thumbnailUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&auto=format&fit=crop&q=80',
            bannerDesktopUrl: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=1920&auto=format&fit=crop&q=80',
            bannerMobileUrl: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=800&auto=format&fit=crop&q=80',
            imageAltText: 'Interactive smart fitness mirror display with virtual personal trainer',
            includeInMenu: true,
            isFeatured: true,
            badge: { text: 'AI-POWERED', color: 'emerald' },
            filterableAttributes: ['brand', 'display_size', 'ai_form_tracking', 'connectivity', 'max_resistance'],
            seo: {
              metaTitle: 'Smart Connected Fitness Mirrors & Digital Gyms | ZYLO',
              metaDescription: 'Transform your space with AI-enabled digital resistance cables and live streaming fitness classes.',
              keywords: ['smart home gym', 'fitness mirror', 'ai workout trainer'],
              canonicalUrl: 'https://zylo.com/categories/smart-connected-fitness',
              ogImage: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=1200&auto=format&fit=crop&q=80',
            },
          },
        ],
      },
      {
        name: 'Outdoor, Hiking & Trekking Gear',
        slug: 'outdoor-camping-trekking',
        description: 'Ultralight waterproof alpine tents, thermal sleeping systems, and titanium camp stoves for backcountry trail blazing.',
        displayOrder: 2,
        iconUrl: 'https://api.iconify.design/lucide:compass.svg?color=%234f46e5',
        thumbnailUrl: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&auto=format&fit=crop&q=80',
        bannerDesktopUrl: 'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=1920&auto=format&fit=crop&q=80',
        bannerMobileUrl: 'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=800&auto=format&fit=crop&q=80',
        imageAltText: 'Glowing high altitude expedition tent beneath alpine twilight sky',
        includeInMenu: true,
        isFeatured: false,
        badge: { text: 'ADVENTURE', color: 'rose' },
        filterableAttributes: ['brand', 'capacity_persons', 'weight_kg', 'waterproof_rating_mm', 'season'],
        seo: {
          metaTitle: 'Alpine Hiking, Camping & Backpacking Gear | ZYLO Outdoors',
          metaDescription: 'Conquer any summit with lightweight trekking gear, durable camping shelters, and weatherproof survival tools.',
          keywords: ['hiking gear', 'camping tents', 'backpacking equipment'],
          canonicalUrl: 'https://zylo.com/categories/outdoor-camping-trekking',
          ogImage: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=1200&auto=format&fit=crop&q=80',
        },
      },
    ],
  },
  {
    name: 'Watches & Fine Horology',
    slug: 'watches-fine-horology',
    description: 'Masterfully crafted mechanical chronographs, Swiss chronometers, and precision titanium smart timepieces.',
    displayOrder: 6,
    iconUrl: 'https://api.iconify.design/lucide:watch.svg?color=%234f46e5',
    thumbnailUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&auto=format&fit=crop&q=80',
    bannerDesktopUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=1920&auto=format&fit=crop&q=80',
    bannerMobileUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&auto=format&fit=crop&q=80',
    imageAltText: 'Close up macro photograph of mechanical watch skeleton movement and gold balance wheel',
    includeInMenu: true,
    isFeatured: true,
    badge: { text: 'TIMELESS', color: 'amber' },
    filterableAttributes: ['brand', 'movement_type', 'case_material', 'water_resistance', 'gender', 'dial_color'],
    seo: {
      metaTitle: 'Luxury Watches & Swiss Automatic Timepieces | ZYLO Horology',
      metaDescription: 'Discover handcrafted mechanical watches, iconic chronographs, and haute horology timepieces from prestigious houses.',
      keywords: ['luxury watches', 'swiss watches', 'automatic chronographs', 'zylo horology'],
      canonicalUrl: 'https://zylo.com/categories/watches-fine-horology',
      ogImage: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=1200&auto=format&fit=crop&q=80',
    },
    children: [
      {
        name: 'Swiss Automatic Timepieces',
        slug: 'swiss-automatic-watches',
        description: 'Certified chronometer movements, sapphire crystal displays, and heritage Swiss complications.',
        displayOrder: 1,
        iconUrl: 'https://api.iconify.design/lucide:clock.svg?color=%234f46e5',
        thumbnailUrl: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=600&auto=format&fit=crop&q=80',
        bannerDesktopUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=1920&auto=format&fit=crop&q=80',
        bannerMobileUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&auto=format&fit=crop&q=80',
        imageAltText: 'Classic Swiss stainless steel automatic dress watch with dark leather strap',
        includeInMenu: true,
        isFeatured: true,
        badge: { text: 'SWISS MADE', color: 'rose' },
        filterableAttributes: ['brand', 'power_reserve_hours', 'crystal', 'strap_material', 'diameter_mm'],
        seo: {
          metaTitle: 'Swiss Automatic & Mechanical Dress Watches | ZYLO',
          metaDescription: 'Shop certified Swiss automatic timepieces featuring open heart balances and precision movements.',
          keywords: ['swiss automatic watch', 'mechanical timepieces', 'sapphire crystal watch'],
          canonicalUrl: 'https://zylo.com/categories/swiss-automatic-watches',
          ogImage: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=1200&auto=format&fit=crop&q=80',
        },
        children: [
          {
            name: 'Luxury Diver & Racing Chronographs',
            slug: 'luxury-chronographs',
            description: '300-meter helium escape diver watches, ceramic tachymeter bezels, and column wheel movements.',
            displayOrder: 1,
            iconUrl: 'https://api.iconify.design/lucide:shield.svg?color=%234f46e5',
            thumbnailUrl: 'https://images.unsplash.com/photo-1539185441755-769473a23570?w=600&auto=format&fit=crop&q=80',
            bannerDesktopUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=1920&auto=format&fit=crop&q=80',
            bannerMobileUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
            imageAltText: 'Rugged professional diver chronograph watch with ceramic bezel on dark textured background',
            includeInMenu: true,
            isFeatured: false,
            badge: { text: '300M DIVER', color: 'indigo' },
            filterableAttributes: ['brand', 'depth_rating', 'bezel_material', 'subdials', 'lume_type'],
            seo: {
              metaTitle: 'Professional Diver & Racing Chronographs | ZYLO',
              metaDescription: 'Engineered for extreme depths and motorsports timing. Ceramic bezels and luminous markers.',
              keywords: ['diver watch', 'chronograph', 'racing watch', '300m dive'],
              canonicalUrl: 'https://zylo.com/categories/luxury-chronographs',
              ogImage: 'https://images.unsplash.com/photo-1539185441755-769473a23570?w=1200&auto=format&fit=crop&q=80',
            },
          },
        ],
      },
      {
        name: 'Smart Wearables & Health Trackers',
        slug: 'smart-watches-wearables',
        description: 'Titanium chassis GPS endurance smartwatches, ECG cardiac monitoring, and sapphire display sports trackers.',
        displayOrder: 2,
        iconUrl: 'https://api.iconify.design/lucide:heart-pulse.svg?color=%234f46e5',
        thumbnailUrl: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&auto=format&fit=crop&q=80',
        bannerDesktopUrl: 'https://images.unsplash.com/photo-1510017803434-a899398421b3?w=1920&auto=format&fit=crop&q=80',
        bannerMobileUrl: 'https://images.unsplash.com/photo-1510017803434-a899398421b3?w=800&auto=format&fit=crop&q=80',
        imageAltText: 'Modern fitness smartwatch showing biometric pulse and sports data metrics',
        includeInMenu: true,
        isFeatured: true,
        badge: { text: 'HEALTH TECH', color: 'emerald' },
        filterableAttributes: ['brand', 'os_compatibility', 'battery_days', 'gps', 'sensors', 'water_rating'],
        seo: {
          metaTitle: 'Smartwatches & Advanced Health Trackers | ZYLO',
          metaDescription: 'Monitor fitness, sleep, and heart rate with high performance GPS smartwatches.',
          keywords: ['smartwatch', 'fitness tracker', 'gps watch', 'health metrics'],
          canonicalUrl: 'https://zylo.com/categories/smart-watches-wearables',
          ogImage: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=1200&auto=format&fit=crop&q=80',
        },
      },
    ],
  },
  {
    name: 'Kitchen, Dining & Culinary Arts',
    slug: 'kitchen-dining-culinary',
    description: 'Commercial grade kitchen appliances, artisanal Japanese knives, and pro barista specialty coffee stations.',
    displayOrder: 7,
    iconUrl: 'https://api.iconify.design/lucide:coffee.svg?color=%234f46e5',
    thumbnailUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&auto=format&fit=crop&q=80',
    bannerDesktopUrl: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=1920&auto=format&fit=crop&q=80',
    bannerMobileUrl: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=800&auto=format&fit=crop&q=80',
    imageAltText: 'Modern luxury kitchen interior with granite island counter and premium cookware',
    includeInMenu: true,
    isFeatured: true,
    badge: { text: 'GOURMET', color: 'amber' },
    filterableAttributes: ['brand', 'material', 'power_watts', 'dishwasher_safe', 'color'],
    seo: {
      metaTitle: 'Kitchen Appliances & Gourmet Cookware | ZYLO Kitchen',
      metaDescription: 'Equip your home kitchen with chef grade cookware, dual-boiler espresso gear, and fine tableware.',
      keywords: ['kitchenware', 'espresso machines', 'chef cookware', 'zylo dining'],
      canonicalUrl: 'https://zylo.com/categories/kitchen-dining-culinary',
      ogImage: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=1200&auto=format&fit=crop&q=80',
    },
    children: [
      {
        name: 'Specialty Espresso & Coffee Gear',
        slug: 'specialty-espresso-coffee',
        description: 'Single-dose conical burr grinders, precision temperature gooseneck kettles, and lever espresso extractors.',
        displayOrder: 1,
        iconUrl: 'https://api.iconify.design/lucide:cup-soda.svg?color=%234f46e5',
        thumbnailUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80',
        bannerDesktopUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1920&auto=format&fit=crop&q=80',
        bannerMobileUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&auto=format&fit=crop&q=80',
        imageAltText: 'Artisan ceramic mug and chrome lever espresso machine in third-wave specialty cafe',
        includeInMenu: true,
        isFeatured: true,
        badge: { text: 'BARISTA', color: 'indigo' },
        filterableAttributes: ['brand', 'boiler_type', 'pump_pressure_bar', 'grinder_burr_mm', 'pid_temp_control'],
        seo: {
          metaTitle: 'Specialty Coffee Makers & Espresso Machines | ZYLO',
          metaDescription: 'Master the perfect espresso pull with precision temperature stability and flat burr grinders.',
          keywords: ['espresso machine', 'coffee grinder', 'barista tools', 'specialty coffee'],
          canonicalUrl: 'https://zylo.com/categories/specialty-espresso-coffee',
          ogImage: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=1200&auto=format&fit=crop&q=80',
        },
        children: [
          {
            name: 'Prosumer Dual-Boiler Machines',
            slug: 'prosumer-espresso-machines',
            description: 'Rotary pump Italian dual-boiler espresso stations with saturated groupheads and flow profiling.',
            displayOrder: 1,
            iconUrl: 'https://api.iconify.design/lucide:flame.svg?color=%234f46e5',
            thumbnailUrl: 'https://images.unsplash.com/photo-1570968915860-54d5c301fa9f?w=600&auto=format&fit=crop&q=80',
            bannerDesktopUrl: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=1920&auto=format&fit=crop&q=80',
            bannerMobileUrl: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800&auto=format&fit=crop&q=80',
            imageAltText: 'Italian stainless steel commercial espresso machine extracting golden crema',
            includeInMenu: true,
            isFeatured: false,
            badge: { text: 'PRO-GRADE', color: 'amber' },
            filterableAttributes: ['brand', 'boiler_capacity_liters', 'water_source', 'plumbed_in', 'flow_profiling'],
            seo: {
              metaTitle: 'Prosumer Dual Boiler Espresso Stations | ZYLO',
              metaDescription: 'Commercial Italian espresso engineering for the true coffee connoisseur home setup.',
              keywords: ['dual boiler espresso', 'italian espresso machine', 'rotary pump'],
              canonicalUrl: 'https://zylo.com/categories/prosumer-espresso-machines',
              ogImage: 'https://images.unsplash.com/photo-1570968915860-54d5c301fa9f?w=1200&auto=format&fit=crop&q=80',
            },
          },
        ],
      },
      {
        name: 'Artisan Cast Iron & Copper Cookware',
        slug: 'cast-iron-cookware',
        description: 'Enameled French Dutch ovens, hand-hammered copper sauté pans, and pre-seasoned skillet collections.',
        displayOrder: 2,
        iconUrl: 'https://api.iconify.design/lucide:utensils.svg?color=%234f46e5',
        thumbnailUrl: 'https://images.unsplash.com/photo-1584990347449-399d5059d45e?w=600&auto=format&fit=crop&q=80',
        bannerDesktopUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=1920&auto=format&fit=crop&q=80',
        bannerMobileUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80',
        imageAltText: 'Classic round enameled cast iron Dutch oven cocotte on rustic wooden kitchen table',
        includeInMenu: true,
        isFeatured: false,
        badge: { text: 'HERITAGE', color: 'rose' },
        filterableAttributes: ['brand', 'material', 'induction_compatible', 'capacity_qt', 'heat_resistance_f'],
        seo: {
          metaTitle: 'Enameled Cast Iron Dutch Ovens & Copper Pots | ZYLO',
          metaDescription: 'Heirloom quality enameled Dutch ovens and copper cookware for slow braising and searing.',
          keywords: ['cast iron dutch oven', 'copper cookware', 'artisan pots'],
          canonicalUrl: 'https://zylo.com/categories/cast-iron-cookware',
          ogImage: 'https://images.unsplash.com/photo-1584990347449-399d5059d45e?w=1200&auto=format&fit=crop&q=80',
        },
      },
    ],
  },
  {
    name: 'Gaming, Consoles & Virtual Reality',
    slug: 'gaming-vr-esports',
    description: 'Next-generation consoles, spatial reality headsets, mechanical esports controllers, and racing simulators.',
    displayOrder: 8,
    iconUrl: 'https://api.iconify.design/lucide:gamepad.svg?color=%234f46e5',
    thumbnailUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80',
    bannerDesktopUrl: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=1920&auto=format&fit=crop&q=80',
    bannerMobileUrl: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=800&auto=format&fit=crop&q=80',
    imageAltText: 'Futuristic gaming setup illuminated with neon cyberpunk blue and magenta LEDs',
    includeInMenu: true,
    isFeatured: true,
    badge: { text: 'ESPORTS', color: 'indigo' },
    filterableAttributes: ['brand', 'platform', 'connectivity', 'resolution', 'refresh_rate'],
    seo: {
      metaTitle: 'Next-Gen Video Game Consoles & VR Gear | ZYLO Gaming',
      metaDescription: 'Shop cutting-edge gaming consoles, wireless pro controllers, and immersive virtual reality rigs.',
      keywords: ['gaming consoles', 'virtual reality', 'vr headsets', 'zylo gaming'],
      canonicalUrl: 'https://zylo.com/categories/gaming-vr-esports',
      ogImage: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&auto=format&fit=crop&q=80',
    },
    children: [
      {
        name: 'Next-Gen Consoles & Hardware',
        slug: 'nextgen-gaming-consoles',
        description: 'Ray-tracing console platforms, SSD expansion cartridges, and custom mechanical trigger controllers.',
        displayOrder: 1,
        iconUrl: 'https://api.iconify.design/lucide:tv.svg?color=%234f46e5',
        thumbnailUrl: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=600&auto=format&fit=crop&q=80',
        bannerDesktopUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=1920&auto=format&fit=crop&q=80',
        bannerMobileUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&auto=format&fit=crop&q=80',
        imageAltText: 'Modern white gaming console and ergonomic dual gamepad controller',
        includeInMenu: true,
        isFeatured: true,
        badge: { text: '4K 120FPS', color: 'emerald' },
        filterableAttributes: ['brand', 'storage_capacity', 'disc_edition', 'hdr_support', 'color'],
        seo: {
          metaTitle: 'Next-Gen Consoles & High Performance Accessories | ZYLO',
          metaDescription: 'Experience true 4K 120FPS gameplay with the latest home video gaming consoles and wireless controllers.',
          keywords: ['gaming console', '4k gaming', 'wireless controller'],
          canonicalUrl: 'https://zylo.com/categories/nextgen-gaming-consoles',
          ogImage: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=1200&auto=format&fit=crop&q=80',
        },
      },
      {
        name: 'Spatial Computing & VR Headsets',
        slug: 'virtual-reality-headsets',
        description: 'Stand-alone OLED microdisplay VR headsets, pancake optics, hand tracking, and 6DoF room-scale spatial audio.',
        displayOrder: 2,
        iconUrl: 'https://api.iconify.design/lucide:eye.svg?color=%234f46e5',
        thumbnailUrl: 'https://images.unsplash.com/photo-1622979135225-d2ba269bc1df?w=600&auto=format&fit=crop&q=80',
        bannerDesktopUrl: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=1920&auto=format&fit=crop&q=80',
        bannerMobileUrl: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=800&auto=format&fit=crop&q=80',
        imageAltText: 'Sleek white spatial computing virtual reality headset on studio background',
        includeInMenu: true,
        isFeatured: false,
        badge: { text: 'SPATIAL 3D', color: 'rose' },
        filterableAttributes: ['brand', 'resolution_per_eye', 'fov_degrees', 'weight_grams', 'passthrough'],
        seo: {
          metaTitle: 'Virtual Reality Headsets & Mixed Reality Spatial Gear | ZYLO',
          metaDescription: 'Step into photorealistic virtual worlds with ultra-high resolution pancake lenses and spatial audio.',
          keywords: ['vr headset', 'spatial computing', 'mixed reality', 'virtual worlds'],
          canonicalUrl: 'https://zylo.com/categories/virtual-reality-headsets',
          ogImage: 'https://images.unsplash.com/photo-1622979135225-d2ba269bc1df?w=1200&auto=format&fit=crop&q=80',
        },
      },
    ],
  },
  {
    name: 'Automotive & Clean Electric Mobility',
    slug: 'automotive-electric-mobility',
    description: 'Smart connected commuter electric scooters, all-terrain e-bikes, and level 2 smart EV charging home stations.',
    displayOrder: 9,
    iconUrl: 'https://api.iconify.design/lucide:car.svg?color=%234f46e5',
    thumbnailUrl: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=600&auto=format&fit=crop&q=80',
    bannerDesktopUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=1920&auto=format&fit=crop&q=80',
    bannerMobileUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&auto=format&fit=crop&q=80',
    imageAltText: 'Modern electric mobility scooter parked in sunlit urban plaza',
    includeInMenu: true,
    isFeatured: true,
    badge: { text: 'ZERO EMISSION', color: 'emerald' },
    filterableAttributes: ['brand', 'battery_range_km', 'top_speed_kmh', 'motor_watts', 'foldable'],
    seo: {
      metaTitle: 'Electric Scooters & Clean Urban Mobility | ZYLO',
      metaDescription: 'Glide past city traffic with long-range electric scooters, folding e-bikes, and rapid EV charging stations.',
      keywords: ['electric scooter', 'ebike', 'ev charging', 'urban mobility'],
      canonicalUrl: 'https://zylo.com/categories/automotive-electric-mobility',
      ogImage: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=1200&auto=format&fit=crop&q=80',
    },
    children: [
      {
        name: 'Electric Scooters & E-Bikes',
        slug: 'electric-urban-mobility',
        description: 'Aircraft aluminum commuter scooters with regenerative braking, dual motors, and pneumatic tires.',
        displayOrder: 1,
        iconUrl: 'https://api.iconify.design/lucide:zap.svg?color=%234f46e5',
        thumbnailUrl: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=600&auto=format&fit=crop&q=80',
        bannerDesktopUrl: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=1920&auto=format&fit=crop&q=80',
        bannerMobileUrl: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=800&auto=format&fit=crop&q=80',
        imageAltText: 'Minimalist matte black electric commuter kick scooter standing on sidewalk',
        includeInMenu: true,
        isFeatured: true,
        badge: { text: '45KM RANGE', color: 'indigo' },
        filterableAttributes: ['brand', 'range_km', 'max_speed_kmh', 'wheel_size_inch', 'suspension'],
        seo: {
          metaTitle: 'Long Range Commuter Electric Scooters | ZYLO',
          metaDescription: 'Foldable electric scooters built with aerospace-grade alloy and dual regenerative disc brakes.',
          keywords: ['electric scooter', 'commuter scooter', 'dual motor scooter'],
          canonicalUrl: 'https://zylo.com/categories/electric-urban-mobility',
          ogImage: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=1200&auto=format&fit=crop&q=80',
        },
      },
    ],
  },
  {
    name: 'Books, Stationery & Executive Craft',
    slug: 'books-fine-stationery',
    description: 'Gold-nib fountain pens, Italian full-grain leather journals, and limited edition art and architecture monographs.',
    displayOrder: 10,
    iconUrl: 'https://api.iconify.design/lucide:book-open.svg?color=%234f46e5',
    thumbnailUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
    bannerDesktopUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=1920&auto=format&fit=crop&q=80',
    bannerMobileUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&auto=format&fit=crop&q=80',
    imageAltText: 'Leather bound notebook beside fountain pen and brass reading spectacles',
    includeInMenu: true,
    isFeatured: false,
    badge: { text: 'EXECUTIVE', color: 'amber' },
    filterableAttributes: ['brand', 'nib_size', 'paper_weight_gsm', 'cover_material', 'binding_type'],
    seo: {
      metaTitle: 'Fine Writing Instruments & Executive Stationery | ZYLO',
      metaDescription: 'Curate your executive desk with 14K gold nib fountain pens, archival notebooks, and luxury desk accessories.',
      keywords: ['fountain pens', 'leather journals', 'stationery', 'zylo books'],
      canonicalUrl: 'https://zylo.com/categories/books-fine-stationery',
      ogImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=1200&auto=format&fit=crop&q=80',
    },
    children: [
      {
        name: 'Fine Fountain Pens & Leather Notebooks',
        slug: 'fountain-pens-leather-journals',
        description: 'Handcrafted resin fountain pens with iridium points, archival acid-free paper, and refillable ink bottles.',
        displayOrder: 1,
        iconUrl: 'https://api.iconify.design/lucide:pen-tool.svg?color=%234f46e5',
        thumbnailUrl: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=600&auto=format&fit=crop&q=80',
        bannerDesktopUrl: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=1920&auto=format&fit=crop&q=80',
        bannerMobileUrl: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&auto=format&fit=crop&q=80',
        imageAltText: 'Classic black and gold fountain pen resting across an open hand-stitched diary',
        includeInMenu: true,
        isFeatured: false,
        badge: { text: 'HANDMADE', color: 'rose' },
        filterableAttributes: ['brand', 'nib_grade', 'fill_mechanism', 'ink_color', 'barrel_material'],
        seo: {
          metaTitle: 'Artisan Fountain Pens & Handbound Leather Journals | ZYLO',
          metaDescription: 'Shop exquisite writing instruments and heavy cotton rag paper notebooks.',
          keywords: ['fountain pen', 'leather journal', 'calligraphy', 'desk craft'],
          canonicalUrl: 'https://zylo.com/categories/fountain-pens-leather-journals',
          ogImage: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=1200&auto=format&fit=crop&q=80',
        },
      },
    ],
  },
];

@Injectable()
export class CategoriesSeedService implements OnModuleInit {
  private readonly logger = new Logger(CategoriesSeedService.name);

  constructor(
    @InjectModel(Category.name)
    private readonly categoryModel: Model<CategoryDocument>,
    private readonly categoriesService: CategoriesService,
  ) {}

  async onModuleInit() {
    await this.seedCategories();
  }

  async seedCategories(): Promise<{ seeded: number; existing: number }> {
    const count = await this.categoryModel.countDocuments();
    if (count < 30) {
      this.logger.log(`Categories catalog currently contains ${count} categories. Resetting and seeding full 31 category suite...`);
      await this.categoryModel.deleteMany({});
    } else {
      this.logger.log(`Categories catalog already contains ${count} categories. Skipping seed.`);
      return { seeded: 0, existing: count };
    }

    this.logger.log('Seeding 31 high-fidelity retail categories across 3 hierarchy levels...');
    let seeded = 0;

    for (const rootDef of SEED_CATEGORIES) {
      const rootDoc = await this.categoriesService.create({
        name: rootDef.name,
        slug: rootDef.slug,
        description: rootDef.description,
        parentId: null,
        displayOrder: rootDef.displayOrder,
        iconUrl: rootDef.iconUrl,
        thumbnailUrl: rootDef.thumbnailUrl,
        bannerDesktopUrl: rootDef.bannerDesktopUrl,
        bannerMobileUrl: rootDef.bannerMobileUrl,
        imageAltText: rootDef.imageAltText,
        includeInMenu: rootDef.includeInMenu,
        isFeatured: rootDef.isFeatured,
        badge: rootDef.badge,
        filterableAttributes: rootDef.filterableAttributes,
        seo: rootDef.seo,
      });
      seeded++;

      if (rootDef.children) {
        for (const childDef of rootDef.children) {
          const childDoc = await this.categoriesService.create({
            name: childDef.name,
            slug: childDef.slug,
            description: childDef.description,
            parentId: rootDoc._id.toString(),
            displayOrder: childDef.displayOrder,
            iconUrl: childDef.iconUrl,
            thumbnailUrl: childDef.thumbnailUrl,
            bannerDesktopUrl: childDef.bannerDesktopUrl,
            bannerMobileUrl: childDef.bannerMobileUrl,
            imageAltText: childDef.imageAltText,
            includeInMenu: childDef.includeInMenu,
            isFeatured: childDef.isFeatured,
            badge: childDef.badge,
            filterableAttributes: childDef.filterableAttributes,
            seo: childDef.seo,
          });
          seeded++;

          if (childDef.children) {
            for (const grandChildDef of childDef.children) {
              await this.categoriesService.create({
                name: grandChildDef.name,
                slug: grandChildDef.slug,
                description: grandChildDef.description,
                parentId: childDoc._id.toString(),
                displayOrder: grandChildDef.displayOrder,
                iconUrl: grandChildDef.iconUrl,
                thumbnailUrl: grandChildDef.thumbnailUrl,
                bannerDesktopUrl: grandChildDef.bannerDesktopUrl,
                bannerMobileUrl: grandChildDef.bannerMobileUrl,
                imageAltText: grandChildDef.imageAltText,
                includeInMenu: grandChildDef.includeInMenu,
                isFeatured: grandChildDef.isFeatured,
                badge: grandChildDef.badge,
                filterableAttributes: grandChildDef.filterableAttributes,
                seo: grandChildDef.seo,
              });
              seeded++;
            }
          }
        }
      }
    }

    this.logger.log(`Successfully seeded ${seeded} retail categories with multi-level hierarchies.`);
    return { seeded, existing: 0 };
  }
}
