import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model, Types } from 'mongoose';
import { Product, ProductDocument } from './schemas/product.schema';
import { Brand, BrandDocument } from '../brands/schemas/brand.schema';
import { Category, CategoryDocument } from '../categories/schemas/category.schema';

interface SeedProductRaw {
  name: string;
  slug: string;
  sku: string;
  categorySlug: string;
  brandSlug: string;
  shortDescription: string;
  description: string;
  basePrice: number;
  salePrice?: number;
  costPrice?: number;
  stockQuantity: number;
  lowStockThreshold?: number;
  isFeatured?: boolean;
  isNewArrival?: boolean;
  tags: string[];
  thumbnailUrl: string;
  images: { url: string; altText: string; isPrimary: boolean; displayOrder: number }[];
  specifications: { group: string; key: string; value: string }[];
  hasVariants?: boolean;
  variants?: {
    sku: string;
    title: string;
    price: number;
    salePrice?: number;
    stockQuantity: number;
    attributes: Record<string, string>;
  }[];
  seo: {
    metaTitle: string;
    metaDescription: string;
    keywords: string[];
    canonicalUrl: string;
    ogImage: string;
  };
}

const SEED_PRODUCTS: SeedProductRaw[] = [
  {
    name: 'Apple iPhone 16 Pro Max',
    slug: 'apple-iphone-16-pro-max',
    sku: 'APL-IP16PM-256',
    categorySlug: 'smartphones',
    brandSlug: 'apple',
    shortDescription: 'Grade 5 Titanium design with A18 Pro chip, 48MP Fusion camera system, and Camera Control button.',
    description: 'iPhone 16 Pro Max is forged in titanium, with the thin borders on any Apple product. Powered by the groundbreaking A18 Pro chip, introducing Camera Control for swift photo capture, 4K 120 fps Dolby Vision recording, and exceptional battery life.',
    basePrice: 1199,
    salePrice: 1149,
    costPrice: 850,
    stockQuantity: 42,
    lowStockThreshold: 10,
    isFeatured: true,
    isNewArrival: true,
    tags: ['iphone', 'apple', 'smartphone', '5g', 'titanium', 'a18 pro'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=1200&auto=format&fit=crop&q=80', altText: 'iPhone 16 Pro Max Titanium', isPrimary: true, displayOrder: 1 },
      { url: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=1200&auto=format&fit=crop&q=80', altText: 'iPhone 16 Pro Max Display', isPrimary: false, displayOrder: 2 },
    ],
    specifications: [
      { group: 'Performance', key: 'Processor', value: 'Apple A18 Pro (3nm)' },
      { group: 'Display', key: 'Screen Size', value: '6.9-inch Super Retina XDR OLED' },
      { group: 'Display', key: 'Refresh Rate', value: '120Hz ProMotion with Always-On' },
      { group: 'Camera', key: 'Main Camera', value: '48MP Fusion + 48MP Ultra Wide + 12MP 5x Telephoto' },
      { group: 'Battery', key: 'Battery Life', value: 'Up to 33 hours video playback' },
    ],
    hasVariants: true,
    variants: [
      { sku: 'APL-IP16PM-256-BLK', title: 'Black Titanium / 256GB', price: 1199, stockQuantity: 15, attributes: { Color: 'Black Titanium', Storage: '256GB' } },
      { sku: 'APL-IP16PM-512-NAT', title: 'Natural Titanium / 512GB', price: 1399, stockQuantity: 18, attributes: { Color: 'Natural Titanium', Storage: '512GB' } },
      { sku: 'APL-IP16PM-1TB-DES', title: 'Desert Titanium / 1TB', price: 1599, stockQuantity: 9, attributes: { Color: 'Desert Titanium', Storage: '1TB' } },
    ],
    seo: {
      metaTitle: 'Apple iPhone 16 Pro Max | Official Store at ZYLO',
      metaDescription: 'Buy the Apple iPhone 16 Pro Max with A18 Pro chip and Grade 5 Titanium finish at ZYLO.',
      keywords: ['iphone 16 pro max', 'apple', 'zylo apple', 'titanium iphone'],
      canonicalUrl: 'https://zylo.com/products/apple-iphone-16-pro-max',
      ogImage: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=1200',
    },
  },
  {
    name: 'Apple MacBook Pro 16" M3 Max',
    slug: 'apple-macbook-pro-16-m3-max',
    sku: 'APL-MBP16-M3M',
    categorySlug: 'laptops',
    brandSlug: 'apple',
    shortDescription: 'Extreme workstation performance with 16-core CPU, 40-core GPU, and Liquid Retina XDR display in Space Black.',
    description: 'MacBook Pro blasts forward with M3 Max, an extraordinarily advanced chip that empowers unprecedented workstation workflows for 3D rendering, machine learning modeling, and high-resolution video grading.',
    basePrice: 3499,
    salePrice: 3299,
    costPrice: 2600,
    stockQuantity: 14,
    lowStockThreshold: 4,
    isFeatured: true,
    isNewArrival: false,
    tags: ['macbook', 'apple', 'm3 max', 'laptop', 'space black', 'pro'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=1200&auto=format&fit=crop&q=80', altText: 'MacBook Pro 16 Space Black', isPrimary: true, displayOrder: 1 },
      { url: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=1200&auto=format&fit=crop&q=80', altText: 'MacBook Pro Keyboard and Trackpad', isPrimary: false, displayOrder: 2 },
    ],
    specifications: [
      { group: 'Performance', key: 'Chip', value: 'Apple M3 Max (16-core CPU, 40-core GPU)' },
      { group: 'Memory', key: 'Unified Memory', value: '48GB Unified RAM' },
      { group: 'Storage', key: 'SSD', value: '1TB Superfast NVMe SSD' },
      { group: 'Display', key: 'Display', value: '16.2-inch Liquid Retina XDR (1600 nits peak)' },
      { group: 'Battery', key: 'Battery Life', value: 'Up to 22 hours' },
    ],
    hasVariants: false,
    variants: [],
    seo: {
      metaTitle: 'Apple MacBook Pro 16" M3 Max | ZYLO Store',
      metaDescription: 'Shop Apple MacBook Pro 16" with M3 Max in Space Black with express delivery.',
      keywords: ['macbook pro 16', 'apple m3 max', 'pro laptop'],
      canonicalUrl: 'https://zylo.com/products/apple-macbook-pro-16-m3-max',
      ogImage: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=1200',
    },
  },
  {
    name: 'Sony WH-1000XM5 Wireless Headphones',
    slug: 'sony-wh-1000xm5-wireless-headphones',
    sku: 'SNY-WH1000XM5',
    categorySlug: 'audio',
    brandSlug: 'sony',
    shortDescription: 'Industry-leading noise canceling with two processors, eight microphones, and ultra-comfortable lightweight design.',
    description: 'The WH-1000XM5 headphones rewrite the rules for distraction-free listening. Two processors control eight microphones for unprecedented active noise cancellation and crystal-clear call quality.',
    basePrice: 399,
    salePrice: 348,
    costPrice: 240,
    stockQuantity: 58,
    lowStockThreshold: 12,
    isFeatured: true,
    isNewArrival: false,
    tags: ['sony', 'headphones', 'noise canceling', 'bluetooth', 'audio', 'anc'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1200&auto=format&fit=crop&q=80', altText: 'Sony WH-1000XM5 Black', isPrimary: true, displayOrder: 1 },
      { url: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=1200&auto=format&fit=crop&q=80', altText: 'Sony WH-1000XM5 Angle', isPrimary: false, displayOrder: 2 },
    ],
    specifications: [
      { group: 'Audio', key: 'Driver Unit', value: '30mm carbon fiber composite' },
      { group: 'Battery', key: 'Battery Life', value: 'Up to 30 hours with ANC on' },
      { group: 'Connectivity', key: 'Bluetooth', value: 'Bluetooth 5.2 (LDAC, AAC, SBC)' },
      { group: 'Weight', key: 'Weight', value: 'Approx. 250g' },
    ],
    hasVariants: true,
    variants: [
      { sku: 'SNY-WH1000XM5-BLK', title: 'Black', price: 399, salePrice: 348, stockQuantity: 32, attributes: { Color: 'Black' } },
      { sku: 'SNY-WH1000XM5-SLV', title: 'Silver', price: 399, salePrice: 348, stockQuantity: 26, attributes: { Color: 'Silver' } },
    ],
    seo: {
      metaTitle: 'Sony WH-1000XM5 Noise Canceling Headphones | ZYLO',
      metaDescription: 'Experience industry-best noise cancellation with Sony WH-1000XM5.',
      keywords: ['sony wh-1000xm5', 'sony headphones', 'anc', 'wireless headphones'],
      canonicalUrl: 'https://zylo.com/products/sony-wh-1000xm5-wireless-headphones',
      ogImage: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1200',
    },
  },
  {
    name: 'Sony PlayStation 5 Pro Console',
    slug: 'sony-playstation-5-pro-console',
    sku: 'SNY-PS5-PRO-2TB',
    categorySlug: 'gaming',
    brandSlug: 'sony',
    shortDescription: 'PlayStation Spectral Super Resolution (PSSR), enhanced ray tracing, and 2TB ultra-fast SSD.',
    description: 'With the PlayStation 5 Pro console, the world’s greatest game creators can enhance their games with incredible features like advanced ray tracing, super sharp image clarity on 4K TVs, and high frame rate gameplay.',
    basePrice: 699,
    salePrice: null,
    costPrice: 580,
    stockQuantity: 19,
    lowStockThreshold: 5,
    isFeatured: true,
    isNewArrival: true,
    tags: ['ps5', 'playstation 5 pro', 'sony', 'gaming', '4k gaming', 'pssr'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=1200&auto=format&fit=crop&q=80', altText: 'PlayStation 5 Console Front', isPrimary: true, displayOrder: 1 },
    ],
    specifications: [
      { group: 'Hardware', key: 'GPU', value: 'Upgraded RDNA Architecture (67% more Compute Units)' },
      { group: 'Storage', key: 'Storage', value: '2TB High-Speed NVMe SSD' },
      { group: 'Video', key: 'Output', value: '4K 120Hz / 8K Support with VRR' },
    ],
    hasVariants: false,
    variants: [],
    seo: {
      metaTitle: 'Sony PlayStation 5 Pro (2TB) | Official Store at ZYLO',
      metaDescription: 'Order the Sony PS5 Pro console with advanced ray tracing and 2TB SSD.',
      keywords: ['ps5 pro', 'playstation 5 pro', 'sony console'],
      canonicalUrl: 'https://zylo.com/products/sony-playstation-5-pro-console',
      ogImage: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=1200',
    },
  },
  {
    name: 'Samsung Galaxy S24 Ultra 5G',
    slug: 'samsung-galaxy-s24-ultra-5g',
    sku: 'SAM-S24U-256',
    categorySlug: 'smartphones',
    brandSlug: 'samsung',
    shortDescription: 'Galaxy AI smartphone with titanium armor, built-in S Pen, and 200MP Quad Telephoto camera.',
    description: 'Welcome to the era of mobile AI. With Galaxy S24 Ultra in your hands, you can unleash whole new levels of creativity, productivity and possibility starting with the most important device in your life.',
    basePrice: 1299,
    salePrice: 1199,
    costPrice: 920,
    stockQuantity: 36,
    lowStockThreshold: 8,
    isFeatured: true,
    isNewArrival: false,
    tags: ['samsung', 'galaxy s24 ultra', 'smartphone', '5g', 'galaxy ai', 's pen'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=1200&auto=format&fit=crop&q=80', altText: 'Samsung Galaxy S24 Ultra Front', isPrimary: true, displayOrder: 1 },
    ],
    specifications: [
      { group: 'Performance', key: 'Processor', value: 'Snapdragon 8 Gen 3 for Galaxy' },
      { group: 'Display', key: 'Screen Size', value: '6.8-inch Dynamic AMOLED 2X (2600 nits)' },
      { group: 'Camera', key: 'Camera', value: '200MP Wide + 50MP 5x Tele + 10MP 3x Tele + 12MP Ultra-Wide' },
      { group: 'Battery', key: 'Battery', value: '5000 mAh' },
    ],
    hasVariants: true,
    variants: [
      { sku: 'SAM-S24U-256-GRY', title: 'Titanium Gray / 256GB', price: 1299, salePrice: 1199, stockQuantity: 20, attributes: { Color: 'Titanium Gray', Storage: '256GB' } },
      { sku: 'SAM-S24U-512-BLK', title: 'Titanium Black / 512GB', price: 1419, salePrice: 1319, stockQuantity: 16, attributes: { Color: 'Titanium Black', Storage: '512GB' } },
    ],
    seo: {
      metaTitle: 'Samsung Galaxy S24 Ultra 5G | ZYLO Store',
      metaDescription: 'Shop Samsung Galaxy S24 Ultra with Galaxy AI and titanium frame.',
      keywords: ['samsung s24 ultra', 'galaxy ai', 'samsung smartphone'],
      canonicalUrl: 'https://zylo.com/products/samsung-galaxy-s24-ultra-5g',
      ogImage: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=1200',
    },
  },
  {
    name: 'Nike Air Jordan 1 Retro High OG',
    slug: 'nike-air-jordan-1-retro-high-og',
    sku: 'NKE-AJ1-OG-CHI',
    categorySlug: 'footwear',
    brandSlug: 'nike',
    shortDescription: 'The classic sneaker that started a global revolution. Premium leather construction with encapsulated Air cushioning.',
    description: 'Familiar shape, fresh colors. The Air Jordan 1 Retro High OG delivers classic style with premium leather and iconic Wings branding that honors Michael Jordan’s legendary debut silhouette.',
    basePrice: 180,
    salePrice: null,
    costPrice: 95,
    stockQuantity: 48,
    lowStockThreshold: 10,
    isFeatured: true,
    isNewArrival: false,
    tags: ['nike', 'jordan', 'sneakers', 'air jordan 1', 'streetwear', 'retro'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?w=1200&auto=format&fit=crop&q=80', altText: 'Air Jordan 1 Retro High OG Side Profile', isPrimary: true, displayOrder: 1 },
      { url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=1200&auto=format&fit=crop&q=80', altText: 'Air Jordan 1 Top View', isPrimary: false, displayOrder: 2 },
    ],
    specifications: [
      { group: 'Materials', key: 'Upper Material', value: '100% Genuine Full-Grain Leather' },
      { group: 'Cushioning', key: 'Midsole', value: 'Encapsulated Nike Air-Sole unit' },
      { group: 'Traction', key: 'Outsole', value: 'Solid rubber outsole with pivot circle' },
    ],
    hasVariants: true,
    variants: [
      { sku: 'NKE-AJ1-OG-US9', title: 'Chicago Colorway / US 9', price: 180, stockQuantity: 12, attributes: { Size: 'US 9', Color: 'Chicago' } },
      { sku: 'NKE-AJ1-OG-US10', title: 'Chicago Colorway / US 10', price: 180, stockQuantity: 20, attributes: { Size: 'US 10', Color: 'Chicago' } },
      { sku: 'NKE-AJ1-OG-US11', title: 'Chicago Colorway / US 11', price: 180, stockQuantity: 16, attributes: { Size: 'US 11', Color: 'Chicago' } },
    ],
    seo: {
      metaTitle: 'Nike Air Jordan 1 Retro High OG | ZYLO Store',
      metaDescription: 'Shop original Nike Air Jordan 1 Retro High OG sneakers at ZYLO.',
      keywords: ['air jordan 1', 'nike retro', 'jordan sneakers'],
      canonicalUrl: 'https://zylo.com/products/nike-air-jordan-1-retro-high-og',
      ogImage: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?w=1200',
    },
  },
  {
    name: 'Adidas Ultraboost Light Running Shoes',
    slug: 'adidas-ultraboost-light-running-shoes',
    sku: 'ADI-UB-LIGHT',
    categorySlug: 'footwear',
    brandSlug: 'adidas',
    shortDescription: 'Epic energy return in our lightest Ultraboost yet, featuring 30% lighter Light BOOST material.',
    description: 'Experience epic energy in every stride with Ultraboost Light, designed with responsive cushioning and a foot-hugging PRIMEKNIT+ upper for daily road running.',
    basePrice: 190,
    salePrice: 149,
    costPrice: 90,
    stockQuantity: 34,
    lowStockThreshold: 8,
    isFeatured: false,
    isNewArrival: true,
    tags: ['adidas', 'ultraboost', 'running', 'boost', 'shoes'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?w=1200&auto=format&fit=crop&q=80', altText: 'Adidas Ultraboost Light White', isPrimary: true, displayOrder: 1 },
    ],
    specifications: [
      { group: 'Cushioning', key: 'Midsole', value: 'Light BOOST midsole technology' },
      { group: 'Upper', key: 'Upper Material', value: 'Adidas PRIMEKNIT+ textile upper' },
      { group: 'Weight', key: 'Weight', value: '293 g (size US 9)' },
    ],
    hasVariants: true,
    variants: [
      { sku: 'ADI-UB-LGT-US9', title: 'Core Black / US 9', price: 190, salePrice: 149, stockQuantity: 14, attributes: { Size: 'US 9', Color: 'Core Black' } },
      { sku: 'ADI-UB-LGT-US10', title: 'Core Black / US 10', price: 190, salePrice: 149, stockQuantity: 20, attributes: { Size: 'US 10', Color: 'Core Black' } },
    ],
    seo: {
      metaTitle: 'Adidas Ultraboost Light Running Shoes | ZYLO',
      metaDescription: 'Shop Adidas Ultraboost Light running shoes with Light BOOST cushioning.',
      keywords: ['adidas ultraboost', 'ultraboost light', 'running shoes'],
      canonicalUrl: 'https://zylo.com/products/adidas-ultraboost-light-running-shoes',
      ogImage: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?w=1200',
    },
  },
  {
    name: 'Dyson V15 Detect Cordless Vacuum',
    slug: 'dyson-v15-detect-cordless-vacuum',
    sku: 'DYS-V15-DET',
    categorySlug: 'appliances',
    brandSlug: 'dyson',
    shortDescription: 'Illumination reveals invisible dust. Piezo sensor scientifically calculates and counts dust particles.',
    description: 'Dyson’s most powerful intelligent cordless vacuum. Features Fluffy Optic cleaner head reveals twice as much invisible dust on hard floors, with an LCD screen showing scientific proof of a deep clean.',
    basePrice: 749,
    salePrice: 649,
    costPrice: 450,
    stockQuantity: 22,
    lowStockThreshold: 5,
    isFeatured: true,
    isNewArrival: false,
    tags: ['dyson', 'v15 detect', 'vacuum', 'cleaning', 'smart home', 'appliances'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=1200&auto=format&fit=crop&q=80', altText: 'Dyson V15 Detect Absolute', isPrimary: true, displayOrder: 1 },
    ],
    specifications: [
      { group: 'Suction', key: 'Suction Power', value: '240 Air Watts' },
      { group: 'Battery', key: 'Run Time', value: 'Up to 60 minutes' },
      { group: 'Filtration', key: 'Filtration', value: 'Whole-machine HEPA filtration (99.99% down to 0.1 microns)' },
      { group: 'Weight', key: 'Weight', value: '3.1 kg' },
    ],
    hasVariants: false,
    variants: [],
    seo: {
      metaTitle: 'Dyson V15 Detect Cordless Vacuum | ZYLO Store',
      metaDescription: 'Buy Dyson V15 Detect with laser dust revelation and HEPA filtration.',
      keywords: ['dyson v15', 'dyson vacuum', 'cordless vacuum'],
      canonicalUrl: 'https://zylo.com/products/dyson-v15-detect-cordless-vacuum',
      ogImage: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=1200',
    },
  },
  {
    name: 'Breville Barista Touch Espresso Machine',
    slug: 'breville-barista-touch-espresso-machine',
    sku: 'BRV-BES880BSS',
    categorySlug: 'appliances',
    brandSlug: 'breville',
    shortDescription: 'Automated touchscreen simplifies how to make your favorite cafe coffee in 3 easy steps.',
    description: 'Cafe quality coffee at home. Innovative ThermoJet heating system achieves optimum extraction temperature in 3 seconds. Automatic microfoam milk texturing delivers silky latte art foam.',
    basePrice: 999,
    salePrice: 899,
    costPrice: 620,
    stockQuantity: 18,
    lowStockThreshold: 4,
    isFeatured: true,
    isNewArrival: false,
    tags: ['breville', 'espresso', 'coffee maker', 'barista touch', 'cafe'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=1200&auto=format&fit=crop&q=80', altText: 'Breville Barista Touch Brushed Stainless', isPrimary: true, displayOrder: 1 },
    ],
    specifications: [
      { group: 'Heating', key: 'Heating System', value: 'ThermoJet (3-second heat up)' },
      { group: 'Milk', key: 'Milk Texturing', value: 'Auto Purge Microfoam texturing' },
      { group: 'Pressure', key: 'Extraction', value: '15 Bar Italian Pump with 9 Bar extraction' },
      { group: 'Grinder', key: 'Integrated Grinder', value: 'Hardened steel conical burrs with 30 settings' },
    ],
    hasVariants: false,
    variants: [],
    seo: {
      metaTitle: 'Breville Barista Touch Espresso Machine | ZYLO',
      metaDescription: 'Shop Breville Barista Touch espresso machine with automated touch screen.',
      keywords: ['breville espresso', 'barista touch', 'espresso maker'],
      canonicalUrl: 'https://zylo.com/products/breville-barista-touch-espresso-machine',
      ogImage: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=1200',
    },
  },
  {
    name: 'Rolex Submariner Date 41mm',
    slug: 'rolex-submariner-date-41mm',
    sku: 'RLX-SUB-126610LN',
    categorySlug: 'watches',
    brandSlug: 'rolex',
    shortDescription: 'Oystersteel with black Cerachrom ceramic bezel and black dial with large luminescent hour markers.',
    description: 'The archetype of the diver’s watch. Unidirectional rotatable 60-minute graduated Cerachrom bezel in ceramic, waterproof to 300 meters (1,000 feet), powered by Calibre 3235 automatic movement.',
    basePrice: 10250,
    salePrice: null,
    costPrice: 7800,
    stockQuantity: 3,
    lowStockThreshold: 2,
    isFeatured: true,
    isNewArrival: false,
    tags: ['rolex', 'submariner', 'luxury watch', 'swiss made', 'oystersteel'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=1200&auto=format&fit=crop&q=80', altText: 'Rolex Submariner Dial', isPrimary: true, displayOrder: 1 },
    ],
    specifications: [
      { group: 'Case', key: 'Case Material', value: 'Oystersteel (904L alloy)' },
      { group: 'Movement', key: 'Calibre', value: 'Rolex Manufacture 3235 Perpetual' },
      { group: 'Waterproof', key: 'Water Resistance', value: 'Waterproof to 300 metres / 1,000 feet' },
      { group: 'Power', key: 'Power Reserve', value: 'Approximately 70 hours' },
    ],
    hasVariants: false,
    variants: [],
    seo: {
      metaTitle: 'Rolex Submariner Date 41mm | Luxury Timepieces at ZYLO',
      metaDescription: 'Authentic Rolex Submariner Date 41mm in Oystersteel with certified manufacturer warranty.',
      keywords: ['rolex submariner', 'rolex 126610LN', 'luxury diver watch'],
      canonicalUrl: 'https://zylo.com/products/rolex-submariner-date-41mm',
      ogImage: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=1200',
    },
  },
  {
    name: 'Lego Star Wars Millennium Falcon UCS',
    slug: 'lego-star-wars-millennium-falcon-ucs',
    sku: 'LGO-SW-75192',
    categorySlug: 'gaming',
    brandSlug: 'lego',
    shortDescription: 'Ultimate Collector Series Millennium Falcon with 7,541 pieces and authentic exterior detailing.',
    description: 'Welcome to the largest, most detailed LEGO Star Wars Millennium Falcon model ever created! Includes 7,541 pieces, interchangeable sensor dishes, and crew figures from both classic and modern trilogies.',
    basePrice: 849,
    salePrice: 799,
    costPrice: 520,
    stockQuantity: 15,
    lowStockThreshold: 3,
    isFeatured: true,
    isNewArrival: false,
    tags: ['lego', 'star wars', 'millennium falcon', 'ucs', 'collector'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1585366119957-e9730b6d0f60?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1585366119957-e9730b6d0f60?w=1200&auto=format&fit=crop&q=80', altText: 'Lego Star Wars Millennium Falcon Box & Build', isPrimary: true, displayOrder: 1 },
    ],
    specifications: [
      { group: 'Details', key: 'Piece Count', value: '7,541 pieces' },
      { group: 'Dimensions', key: 'Dimensions', value: '84cm long, 60cm wide, 21cm high' },
      { group: 'Age', key: 'Age Recommendation', value: '16+' },
    ],
    hasVariants: false,
    variants: [],
    seo: {
      metaTitle: 'LEGO Star Wars Millennium Falcon UCS 75192 | ZYLO',
      metaDescription: 'Order the LEGO Star Wars UCS Millennium Falcon with 7,541 pieces.',
      keywords: ['lego falcon', 'lego ucs', 'star wars 75192'],
      canonicalUrl: 'https://zylo.com/products/lego-star-wars-millennium-falcon-ucs',
      ogImage: 'https://images.unsplash.com/photo-1585366119957-e9730b6d0f60?w=1200',
    },
  },
  {
    name: 'Razer Blade 16 Gaming Laptop',
    slug: 'razer-blade-16-gaming-laptop',
    sku: 'RZR-BLD16-4090',
    categorySlug: 'laptops',
    brandSlug: 'razer',
    shortDescription: 'World’s first dual-mode Mini-LED display with Intel Core i9-14900HX and NVIDIA GeForce RTX 4090.',
    description: 'Experience insane visual clarity and depth with the Razer Blade 16. Switch seamlessly between ultra-sharp 4K 120Hz for creative work and blazing-fast FHD+ 240Hz for competitive gaming.',
    basePrice: 3799,
    salePrice: 3599,
    costPrice: 2800,
    stockQuantity: 9,
    lowStockThreshold: 3,
    isFeatured: true,
    isNewArrival: true,
    tags: ['razer', 'blade 16', 'gaming laptop', 'rtx 4090', 'mini-led'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=1200&auto=format&fit=crop&q=80', altText: 'Razer Blade 16 Open View', isPrimary: true, displayOrder: 1 },
    ],
    specifications: [
      { group: 'Performance', key: 'GPU', value: 'NVIDIA GeForce RTX 4090 (175W TGP)' },
      { group: 'Performance', key: 'CPU', value: 'Intel Core i9-14900HX (24 cores)' },
      { group: 'Display', key: 'Display', value: '16-inch Dual-Mode Mini-LED (4K 120Hz / FHD+ 240Hz)' },
      { group: 'Memory', key: 'RAM', value: '32GB DDR5 5600MHz' },
    ],
    hasVariants: false,
    variants: [],
    seo: {
      metaTitle: 'Razer Blade 16 (RTX 4090) Gaming Laptop | ZYLO',
      metaDescription: 'Shop Razer Blade 16 with RTX 4090 and Dual-Mode Mini-LED display.',
      keywords: ['razer blade 16', 'rtx 4090 laptop', 'gaming notebook'],
      canonicalUrl: 'https://zylo.com/products/razer-blade-16-gaming-laptop',
      ogImage: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=1200',
    },
  },
  {
    name: 'Canon EOS R5 Mark II Mirrorless Camera',
    slug: 'canon-eos-r5-mark-ii-mirrorless-camera',
    sku: 'CAN-R5M2-BODY',
    categorySlug: 'cameras',
    brandSlug: 'canon',
    shortDescription: '45MP back-illuminated stacked sensor with 8K 60p RAW video recording and Eye Control AF.',
    description: 'Master the moment with the EOS R5 Mark II. Combining high-resolution stills with 8K video and next-generation Dual Pixel Intelligent AF powered by accelerated deep learning processors.',
    basePrice: 4299,
    salePrice: null,
    costPrice: 3400,
    stockQuantity: 11,
    lowStockThreshold: 3,
    isFeatured: true,
    isNewArrival: true,
    tags: ['canon', 'eos r5 mark ii', 'camera', 'mirrorless', '8k video', 'photography'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=1200&auto=format&fit=crop&q=80', altText: 'Canon EOS R5 Camera Body', isPrimary: true, displayOrder: 1 },
    ],
    specifications: [
      { group: 'Sensor', key: 'Sensor', value: '45MP Full-Frame Back-Illuminated Stacked CMOS' },
      { group: 'Video', key: 'Video Recording', value: '8K 60p RAW / 4K 120p' },
      { group: 'Autofocus', key: 'Autofocus', value: 'Dual Pixel Intelligent AF with Action Priority' },
    ],
    hasVariants: false,
    variants: [],
    seo: {
      metaTitle: 'Canon EOS R5 Mark II Camera Body | ZYLO',
      metaDescription: 'Shop Canon EOS R5 Mark II mirrorless camera with 45MP stacked sensor and 8K video.',
      keywords: ['canon r5 mark ii', 'canon eos r5', 'pro mirrorless camera'],
      canonicalUrl: 'https://zylo.com/products/canon-eos-r5-mark-ii-mirrorless-camera',
      ogImage: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=1200',
    },
  },
  {
    name: 'Logitech MX Master 3S Wireless Mouse',
    slug: 'logitech-mx-master-3s-wireless-mouse',
    sku: 'LOG-MXM3S-GRY',
    categorySlug: 'laptops',
    brandSlug: 'logitech',
    shortDescription: 'Quiet Click performance mouse with 8K DPI tracking on glass and MagSpeed electromagnetic scroll wheel.',
    description: 'Meet MX Master 3S, an iconic mouse remastered for ultimate tactility, performance, and flow. Quiet Clicks deliver a satisfying soft click feel with 90% less noise.',
    basePrice: 99,
    salePrice: 89,
    costPrice: 55,
    stockQuantity: 74,
    lowStockThreshold: 15,
    isFeatured: false,
    isNewArrival: false,
    tags: ['logitech', 'mx master 3s', 'mouse', 'ergonomic', 'productivity'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=1200&auto=format&fit=crop&q=80', altText: 'Logitech MX Master 3S Top Angle', isPrimary: true, displayOrder: 1 },
    ],
    specifications: [
      { group: 'Sensor', key: 'Sensor Technology', value: 'Darkfield high precision (8000 DPI)' },
      { group: 'Battery', key: 'Battery Life', value: 'Up to 70 days on a single full charge' },
      { group: 'Wireless', key: 'Connectivity', value: 'Logi Bolt USB Receiver or Bluetooth Low Energy' },
    ],
    hasVariants: true,
    variants: [
      { sku: 'LOG-MXM3S-GRPH', title: 'Graphite', price: 99, salePrice: 89, stockQuantity: 44, attributes: { Color: 'Graphite' } },
      { sku: 'LOG-MXM3S-PALE', title: 'Pale Gray', price: 99, salePrice: 89, stockQuantity: 30, attributes: { Color: 'Pale Gray' } },
    ],
    seo: {
      metaTitle: 'Logitech MX Master 3S Wireless Mouse | ZYLO',
      metaDescription: 'Shop Logitech MX Master 3S performance mouse with 8K DPI tracking.',
      keywords: ['logitech mx master 3s', 'wireless mouse', 'ergonomic mouse'],
      canonicalUrl: 'https://zylo.com/products/logitech-mx-master-3s-wireless-mouse',
      ogImage: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=1200',
    },
  },
  {
    name: 'Sonos Era 300 Spatial Audio Speaker',
    slug: 'sonos-era-300-spatial-audio-speaker',
    sku: 'SNS-ERA300-BLK',
    categorySlug: 'audio',
    brandSlug: 'sonos',
    shortDescription: 'Revolutionary spatial audio speaker with Dolby Atmos and six optimally positioned drivers.',
    description: 'Featuring next-level audio that hits from every direction, Era 300 doesn’t just surround you, it puts you inside your music with Dolby Atmos spatial audio.',
    basePrice: 449,
    salePrice: 399,
    costPrice: 280,
    stockQuantity: 28,
    lowStockThreshold: 6,
    isFeatured: true,
    isNewArrival: false,
    tags: ['sonos', 'era 300', 'speaker', 'spatial audio', 'dolby atmos', 'wireless audio'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=1200&auto=format&fit=crop&q=80', altText: 'Sonos Era 300 Speaker Front', isPrimary: true, displayOrder: 1 },
    ],
    specifications: [
      { group: 'Acoustics', key: 'Amplifiers', value: 'Six class-D digital amplifiers' },
      { group: 'Audio', key: 'Audio Format', value: 'Dolby Atmos Music Support' },
      { group: 'Connectivity', key: 'WiFi / Bluetooth', value: 'WiFi 6 + Bluetooth 5.0 + Apple AirPlay 2' },
    ],
    hasVariants: false,
    variants: [],
    seo: {
      metaTitle: 'Sonos Era 300 Spatial Audio Speaker | ZYLO',
      metaDescription: 'Experience Dolby Atmos spatial audio with the Sonos Era 300 smart speaker.',
      keywords: ['sonos era 300', 'spatial audio', 'dolby atmos speaker'],
      canonicalUrl: 'https://zylo.com/products/sonos-era-300-spatial-audio-speaker',
      ogImage: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=1200',
    },
  },
  {
    name: 'Garmin Fenix 7 Pro Solar Multisport Watch',
    slug: 'garmin-fenix-7-pro-solar-multisport-watch',
    sku: 'GRM-FNX7P-SLR',
    categorySlug: 'watches',
    brandSlug: 'garmin',
    shortDescription: 'Ultimate multisport GPS smartwatch with solar charging lens, built-in LED flashlight, and mapping.',
    description: 'Conquer every hour with advanced training features, 24/7 health monitoring, and up to 22 days of battery life in smartwatch mode with solar charging in 3 hours of direct sunlight per day.',
    basePrice: 799,
    salePrice: 699,
    costPrice: 490,
    stockQuantity: 21,
    lowStockThreshold: 5,
    isFeatured: true,
    isNewArrival: false,
    tags: ['garmin', 'fenix 7 pro', 'smartwatch', 'solar', 'fitness', 'gps'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=1200&auto=format&fit=crop&q=80', altText: 'Garmin Fenix 7 Pro Solar Watch', isPrimary: true, displayOrder: 1 },
    ],
    specifications: [
      { group: 'Display', key: 'Lens', value: 'Power Glass with Solar Charging' },
      { group: 'Battery', key: 'Smartwatch Mode', value: 'Up to 22 days with solar' },
      { group: 'Waterproof', key: 'Water Rating', value: '10 ATM (100 meters)' },
    ],
    hasVariants: false,
    variants: [],
    seo: {
      metaTitle: 'Garmin Fenix 7 Pro Solar Multisport Watch | ZYLO',
      metaDescription: 'Shop Garmin Fenix 7 Pro Solar smartwatch with endurance GPS and mapping.',
      keywords: ['garmin fenix 7 pro', 'garmin solar', 'gps watch'],
      canonicalUrl: 'https://zylo.com/products/garmin-fenix-7-pro-solar-multisport-watch',
      ogImage: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=1200',
    },
  },
  {
    name: 'Apple AirPods Max',
    slug: 'apple-airpods-max',
    sku: 'APL-APM-USB-C',
    categorySlug: 'audio',
    brandSlug: 'apple',
    shortDescription: 'High-fidelity audio with Active Noise Cancellation, Transparency mode, and personalized Spatial Audio.',
    description: 'AirPods Max reimagine over-ear headphones. An Apple-designed dynamic driver provides immersive high-fidelity audio. Every detail, from canopy to cushions, has been engineered for an exceptional fit.',
    basePrice: 549,
    salePrice: 499,
    costPrice: 380,
    stockQuantity: 30,
    lowStockThreshold: 6,
    isFeatured: true,
    isNewArrival: true,
    tags: ['apple', 'airpods max', 'headphones', 'spatial audio', 'noise canceling'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=1200&auto=format&fit=crop&q=80', altText: 'AirPods Max Silver', isPrimary: true, displayOrder: 1 },
    ],
    specifications: [
      { group: 'Audio', key: 'Driver', value: 'Apple-designed 40mm dynamic driver' },
      { group: 'Battery', key: 'Battery Life', value: 'Up to 20 hours with ANC / Spatial Audio enabled' },
      { group: 'Charging', key: 'Connector', value: 'USB-C Charging' },
    ],
    hasVariants: true,
    variants: [
      { sku: 'APL-APM-SLV', title: 'Silver', price: 549, salePrice: 499, stockQuantity: 18, attributes: { Color: 'Silver' } },
      { sku: 'APL-APM-MID', title: 'Midnight', price: 549, salePrice: 499, stockQuantity: 12, attributes: { Color: 'Midnight' } },
    ],
    seo: {
      metaTitle: 'Apple AirPods Max Over-Ear Headphones | ZYLO Store',
      metaDescription: 'Shop Apple AirPods Max with computational audio and Active Noise Cancellation.',
      keywords: ['airpods max', 'apple headphones', 'noise canceling'],
      canonicalUrl: 'https://zylo.com/products/apple-airpods-max',
      ogImage: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=1200',
    },
  },
  {
    name: 'Apple iPad Air 11" M2',
    slug: 'apple-ipad-air-11-m2',
    sku: 'APL-IPADAIR-11-M2',
    categorySlug: 'smartphones',
    brandSlug: 'apple',
    shortDescription: 'Redesigned iPad Air powered by the blazing-fast Apple M2 chip and Liquid Retina display.',
    description: 'iPad Air is powered by the incredibly fast Apple M2 chip. It features a stunning Liquid Retina display, a new landscape front camera perfect for FaceTime and video calls, and superfast Wi-Fi 6E.',
    basePrice: 599,
    salePrice: 569,
    costPrice: 420,
    stockQuantity: 28,
    lowStockThreshold: 5,
    isFeatured: true,
    isNewArrival: false,
    tags: ['ipad', 'apple', 'ipad air', 'm2', 'tablet'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=1200&auto=format&fit=crop&q=80', altText: 'iPad Air Display', isPrimary: true, displayOrder: 1 },
    ],
    specifications: [
      { group: 'Performance', key: 'Chip', value: 'Apple M2 (8-core CPU, 10-core GPU)' },
      { group: 'Display', key: 'Screen Size', value: '11-inch Liquid Retina with True Tone' },
      { group: 'Camera', key: 'Front Camera', value: 'Landscape 12MP Ultra Wide with Center Stage' },
    ],
    hasVariants: true,
    variants: [
      { sku: 'APL-AIR11-128-GRY', title: 'Space Gray / 128GB', price: 599, salePrice: 569, stockQuantity: 16, attributes: { Color: 'Space Gray', Storage: '128GB' } },
      { sku: 'APL-AIR11-256-BLU', title: 'Blue / 256GB', price: 699, salePrice: 669, stockQuantity: 12, attributes: { Color: 'Blue', Storage: '256GB' } },
    ],
    seo: {
      metaTitle: 'Apple iPad Air 11" M2 | ZYLO Store',
      metaDescription: 'Shop the Apple iPad Air 11-inch with Apple M2 chip at ZYLO.',
      keywords: ['ipad air', 'apple ipad m2', 'tablet'],
      canonicalUrl: 'https://zylo.com/products/apple-ipad-air-11-m2',
      ogImage: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=1200',
    },
  },
  {
    name: 'Sony Alpha A7R V Full-Frame Camera',
    slug: 'sony-alpha-a7r-v-full-frame-camera',
    sku: 'SNY-A7RV-BODY',
    categorySlug: 'cameras',
    brandSlug: 'sony',
    shortDescription: '61MP Exmor R sensor with dedicated AI processing unit for next-generation subject recognition autofocus.',
    description: 'The Alpha 7R V features an AI processing unit dedicated to deep learning algorithms, plus a 61MP high-resolution back-illuminated sensor and 8-step image stabilization for breathtaking landscape and commercial work.',
    basePrice: 3899,
    salePrice: 3699,
    costPrice: 2900,
    stockQuantity: 8,
    lowStockThreshold: 2,
    isFeatured: true,
    isNewArrival: false,
    tags: ['sony', 'alpha a7r v', 'camera', 'mirrorless', '61mp', 'full frame'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=1200&auto=format&fit=crop&q=80', altText: 'Sony A7R V Camera Front', isPrimary: true, displayOrder: 1 },
    ],
    specifications: [
      { group: 'Sensor', key: 'Sensor Resolution', value: '61.0 Megapixels Full-Frame Exmor R CMOS' },
      { group: 'Stabilization', key: 'IBIS', value: '8.0-stop 5-axis in-body optical image stabilization' },
      { group: 'Video', key: 'Video Resolution', value: '8K 24p / 4K 60p 10-bit 4:2:2' },
    ],
    hasVariants: false,
    variants: [],
    seo: {
      metaTitle: 'Sony Alpha A7R V 61MP Mirrorless Camera | ZYLO',
      metaDescription: 'Order the Sony Alpha A7R V mirrorless camera with AI autofocus and 61MP sensor.',
      keywords: ['sony a7r v', 'sony camera', '61mp full frame'],
      canonicalUrl: 'https://zylo.com/products/sony-alpha-a7r-v-full-frame-camera',
      ogImage: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=1200',
    },
  },
  {
    name: 'Sony WF-1000XM5 Noise Canceling Earbuds',
    slug: 'sony-wf-1000xm5-noise-canceling-earbuds',
    sku: 'SNY-WF1000XM5',
    categorySlug: 'audio',
    brandSlug: 'sony',
    shortDescription: 'The best truly wireless noise canceling earbuds with Dynamic Driver X and dual feedback microphones.',
    description: 'The WF-1000XM5 earbuds feature cutting-edge technology to deliver premium sound quality and the best truly wireless noise-canceling performance on the market.',
    basePrice: 299,
    salePrice: 278,
    costPrice: 180,
    stockQuantity: 44,
    lowStockThreshold: 10,
    isFeatured: false,
    isNewArrival: false,
    tags: ['sony', 'wf-1000xm5', 'earbuds', 'wireless', 'anc'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=1200&auto=format&fit=crop&q=80', altText: 'Sony WF-1000XM5 Earbuds Case', isPrimary: true, displayOrder: 1 },
    ],
    specifications: [
      { group: 'Driver', key: 'Driver Unit', value: '8.4mm Dynamic Driver X' },
      { group: 'Battery', key: 'Total Battery Life', value: 'Up to 24 hours (8h buds + 16h case)' },
      { group: 'Water Resistance', key: 'Rating', value: 'IPX4 water-resistant' },
    ],
    hasVariants: true,
    variants: [
      { sku: 'SNY-WF5-BLK', title: 'Black', price: 299, salePrice: 278, stockQuantity: 24, attributes: { Color: 'Black' } },
      { sku: 'SNY-WF5-SLV', title: 'Silver', price: 299, salePrice: 278, stockQuantity: 20, attributes: { Color: 'Silver' } },
    ],
    seo: {
      metaTitle: 'Sony WF-1000XM5 Wireless Noise Canceling Earbuds | ZYLO',
      metaDescription: 'Shop Sony WF-1000XM5 earbuds with Dynamic Driver X and Hi-Res Wireless Audio.',
      keywords: ['sony wf-1000xm5', 'wireless earbuds', 'sony noise canceling'],
      canonicalUrl: 'https://zylo.com/products/sony-wf-1000xm5-noise-canceling-earbuds',
      ogImage: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=1200',
    },
  },
  {
    name: 'Samsung 65" Neo QLED 4K Smart TV',
    slug: 'samsung-65-neo-qled-4k-smart-tv',
    sku: 'SAM-QN90D-65',
    categorySlug: 'appliances',
    brandSlug: 'samsung',
    shortDescription: 'Quantum Matrix Mini-LED with NQ4 AI Gen2 Processor, Dolby Atmos, and Anti-Glare screen.',
    description: 'Catch every brilliant detail with Samsung Neo QLED 4K. Mini-LED backlighting controls contrast with surgical precision, while 4K AI upscaling transforms everyday entertainment into pure spectacle.',
    basePrice: 1999,
    salePrice: 1799,
    costPrice: 1350,
    stockQuantity: 16,
    lowStockThreshold: 4,
    isFeatured: true,
    isNewArrival: true,
    tags: ['samsung', 'smart tv', 'neo qled', '4k tv', 'mini-led', 'dolby atmos'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=1200&auto=format&fit=crop&q=80', altText: 'Samsung Neo QLED TV Living Room', isPrimary: true, displayOrder: 1 },
    ],
    specifications: [
      { group: 'Display', key: 'Panel Type', value: 'Neo QLED Mini-LED with Anti-Reflection' },
      { group: 'Refresh Rate', key: 'Motion', value: '120Hz Native (Up to 144Hz VRR for gaming)' },
      { group: 'Audio', key: 'Speaker System', value: '60W 4.2.2 Channel Dolby Atmos' },
    ],
    hasVariants: false,
    variants: [],
    seo: {
      metaTitle: 'Samsung 65" Neo QLED 4K Smart TV (QN90D) | ZYLO',
      metaDescription: 'Shop Samsung 65-inch Neo QLED 4K TV with Mini-LED precision lighting.',
      keywords: ['samsung tv', 'neo qled', '65 inch 4k tv'],
      canonicalUrl: 'https://zylo.com/products/samsung-65-neo-qled-4k-smart-tv',
      ogImage: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=1200',
    },
  },
  {
    name: 'Samsung Galaxy Watch 7 Ultra',
    slug: 'samsung-galaxy-watch-7-ultra',
    sku: 'SAM-GW7U-47',
    categorySlug: 'watches',
    brandSlug: 'samsung',
    shortDescription: 'Grade 4 Titanium cushion design with dual-frequency GPS, Sapphire Crystal glass, and 100-hour battery life.',
    description: 'Engineered for extreme endurance. Galaxy Watch Ultra withstands temperatures up to 55°C, 9,000m altitudes, and 10 ATM ocean pressure, powered by BioActive Sensor 2 for real-time fitness metrics.',
    basePrice: 649,
    salePrice: 599,
    costPrice: 420,
    stockQuantity: 25,
    lowStockThreshold: 5,
    isFeatured: true,
    isNewArrival: true,
    tags: ['samsung', 'galaxy watch ultra', 'smartwatch', 'titanium', 'fitness'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=1200&auto=format&fit=crop&q=80', altText: 'Samsung Galaxy Watch Dial', isPrimary: true, displayOrder: 1 },
    ],
    specifications: [
      { group: 'Body', key: 'Case Material', value: 'Grade 4 Titanium with Sapphire Crystal' },
      { group: 'Waterproof', key: 'Rating', value: '10 ATM + IP68 + MIL-STD-810H' },
      { group: 'Battery', key: 'Battery Life', value: 'Up to 100 hours in Power Saving mode' },
    ],
    hasVariants: false,
    variants: [],
    seo: {
      metaTitle: 'Samsung Galaxy Watch 7 Ultra | ZYLO Store',
      metaDescription: 'Shop Samsung Galaxy Watch 7 Ultra with titanium durability and dual GPS.',
      keywords: ['galaxy watch ultra', 'samsung smartwatch', 'titanium watch'],
      canonicalUrl: 'https://zylo.com/products/samsung-galaxy-watch-7-ultra',
      ogImage: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=1200',
    },
  },
  {
    name: 'Nike Pegasus 41 Road Running Shoes',
    slug: 'nike-pegasus-41-road-running-shoes',
    sku: 'NKE-PEG41-MENS',
    categorySlug: 'footwear',
    brandSlug: 'nike',
    shortDescription: 'Responsive daily trainer with all-new ReactX foam midsole and dual Air Zoom units.',
    description: 'Responsive cushioning in the Pegasus provides an energized ride for everyday road running. Experience lighter-weight energy return with dual Air Zoom units and an upgraded engineered mesh upper.',
    basePrice: 140,
    salePrice: 129,
    costPrice: 75,
    stockQuantity: 52,
    lowStockThreshold: 12,
    isFeatured: false,
    isNewArrival: true,
    tags: ['nike', 'pegasus 41', 'running shoes', 'reactx', 'air zoom'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1200&auto=format&fit=crop&q=80', altText: 'Nike Pegasus Red Profile', isPrimary: true, displayOrder: 1 },
    ],
    specifications: [
      { group: 'Cushioning', key: 'Midsole Foam', value: 'Nike ReactX foam (13% more energy return)' },
      { group: 'Air Units', key: 'Air Units', value: 'Forefoot and heel Air Zoom units' },
      { group: 'Weight', key: 'Weight', value: 'Approx. 297g (Men\'s US 10)' },
    ],
    hasVariants: true,
    variants: [
      { sku: 'NKE-PEG41-US9', title: 'Bright Crimson / US 9', price: 140, salePrice: 129, stockQuantity: 16, attributes: { Size: 'US 9', Color: 'Crimson' } },
      { sku: 'NKE-PEG41-US10', title: 'Bright Crimson / US 10', price: 140, salePrice: 129, stockQuantity: 20, attributes: { Size: 'US 10', Color: 'Crimson' } },
      { sku: 'NKE-PEG41-US11', title: 'Bright Crimson / US 11', price: 140, salePrice: 129, stockQuantity: 16, attributes: { Size: 'US 11', Color: 'Crimson' } },
    ],
    seo: {
      metaTitle: 'Nike Pegasus 41 Running Shoes | ZYLO Store',
      metaDescription: 'Shop Nike Pegasus 41 daily running shoes with ReactX foam.',
      keywords: ['nike pegasus 41', 'nike running', 'reactx running shoes'],
      canonicalUrl: 'https://zylo.com/products/nike-pegasus-41-road-running-shoes',
      ogImage: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1200',
    },
  },
  {
    name: 'Nike Tech Fleece Full-Zip Windrunner',
    slug: 'nike-tech-fleece-full-zip-windrunner',
    sku: 'NKE-TF-WINDRUN',
    categorySlug: 'appliances',
    brandSlug: 'nike',
    shortDescription: 'Smooth on both sides, premium lightweight fleece offers warmth without bulk in iconic chevron styling.',
    description: 'Blending two of Nike\'s most iconic looks, this full-zip hoodie draws design inspiration from our timeless Windrunner jacket. Relaxed through shoulders, chest, and body for an athletic profile.',
    basePrice: 145,
    salePrice: null,
    costPrice: 70,
    stockQuantity: 38,
    lowStockThreshold: 8,
    isFeatured: false,
    isNewArrival: false,
    tags: ['nike', 'tech fleece', 'hoodie', 'windrunner', 'sportswear', 'apparel'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=1200&auto=format&fit=crop&q=80', altText: 'Nike Tech Fleece Hoodie Front', isPrimary: true, displayOrder: 1 },
    ],
    specifications: [
      { group: 'Material', key: 'Fabric', value: '53% Cotton / 47% Polyester' },
      { group: 'Pockets', key: 'Storage', value: 'Zippered sleeve pocket + side hand pockets' },
    ],
    hasVariants: true,
    variants: [
      { sku: 'NKE-TF-M', title: 'Black / Size M', price: 145, stockQuantity: 18, attributes: { Size: 'M', Color: 'Black' } },
      { sku: 'NKE-TF-L', title: 'Black / Size L', price: 145, stockQuantity: 20, attributes: { Size: 'L', Color: 'Black' } },
    ],
    seo: {
      metaTitle: 'Nike Tech Fleece Full-Zip Windrunner Hoodie | ZYLO',
      metaDescription: 'Shop Nike Tech Fleece Windrunner full-zip hoodie with lightweight warmth.',
      keywords: ['nike tech fleece', 'windrunner hoodie', 'nike sportswear'],
      canonicalUrl: 'https://zylo.com/products/nike-tech-fleece-full-zip-windrunner',
      ogImage: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=1200',
    },
  },
  {
    name: 'Adidas Predator Elite Firm Ground Cleats',
    slug: 'adidas-predator-elite-firm-ground-cleats',
    sku: 'ADI-PRED-ELITE',
    categorySlug: 'footwear',
    brandSlug: 'adidas',
    shortDescription: 'Precision soccer cleats with Strikeskin rubber fins and lightweight Controlframe 2.0 outsole.',
    description: 'When the goal is in your sights, the adidas Predator converts pressure into pinpoint accuracy. Strategically placed Strikeskin rubber fins grip the ball for clinical swerve and power.',
    basePrice: 280,
    salePrice: 249,
    costPrice: 150,
    stockQuantity: 22,
    lowStockThreshold: 5,
    isFeatured: true,
    isNewArrival: false,
    tags: ['adidas', 'predator', 'soccer cleats', 'football boots', 'strikeskin'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?w=1200&auto=format&fit=crop&q=80', altText: 'Adidas Soccer Cleats Profile', isPrimary: true, displayOrder: 1 },
    ],
    specifications: [
      { group: 'Upper', key: 'Technology', value: 'HybridTouch 2.0 with Strikeskin elements' },
      { group: 'Outsole', key: 'Traction', value: 'Controlframe 2.0 firm ground outsole' },
    ],
    hasVariants: true,
    variants: [
      { sku: 'ADI-PRED-US9', title: 'Solar Red / US 9', price: 280, salePrice: 249, stockQuantity: 10, attributes: { Size: 'US 9' } },
      { sku: 'ADI-PRED-US10', title: 'Solar Red / US 10', price: 280, salePrice: 249, stockQuantity: 12, attributes: { Size: 'US 10' } },
    ],
    seo: {
      metaTitle: 'Adidas Predator Elite Firm Ground Soccer Cleats | ZYLO',
      metaDescription: 'Shop Adidas Predator Elite FG cleats with Strikeskin technology.',
      keywords: ['adidas predator', 'soccer cleats', 'football boots'],
      canonicalUrl: 'https://zylo.com/products/adidas-predator-elite-firm-ground-cleats',
      ogImage: 'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?w=1200',
    },
  },
  {
    name: 'Puma Velocity Nitro 3 Running Shoes',
    slug: 'puma-velocity-nitro-3-running-shoes',
    sku: 'PMA-VN3-MENS',
    categorySlug: 'footwear',
    brandSlug: 'puma',
    shortDescription: 'NITRO advanced nitrogen-injected foam delivers lightweight responsiveness and PUMAGRIP traction.',
    description: 'With the Velocity Nitro 3, Puma brings together unmatched comfort and high-traction durability for running on any road surface, rain or shine.',
    basePrice: 135,
    salePrice: 119,
    costPrice: 68,
    stockQuantity: 36,
    lowStockThreshold: 8,
    isFeatured: false,
    isNewArrival: true,
    tags: ['puma', 'velocity nitro 3', 'running shoes', 'nitro foam'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=1200&auto=format&fit=crop&q=80', altText: 'Puma Velocity Nitro Shoes', isPrimary: true, displayOrder: 1 },
    ],
    specifications: [
      { group: 'Foam', key: 'Midsole', value: 'NITRO advanced foam technology' },
      { group: 'Outsole', key: 'Rubber', value: 'PUMAGRIP all-surface rubber compound' },
    ],
    hasVariants: true,
    variants: [
      { sku: 'PMA-VN3-US9', title: 'Lime Green / US 9', price: 135, salePrice: 119, stockQuantity: 18, attributes: { Size: 'US 9' } },
      { sku: 'PMA-VN3-US10', title: 'Lime Green / US 10', price: 135, salePrice: 119, stockQuantity: 18, attributes: { Size: 'US 10' } },
    ],
    seo: {
      metaTitle: 'Puma Velocity Nitro 3 Running Shoes | ZYLO Store',
      metaDescription: 'Shop Puma Velocity Nitro 3 with nitrogen-infused foam cushioning.',
      keywords: ['puma velocity nitro', 'puma running shoes', 'nitro foam'],
      canonicalUrl: 'https://zylo.com/products/puma-velocity-nitro-3-running-shoes',
      ogImage: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=1200',
    },
  },
  {
    name: 'Under Armour Project Rock Training Hoodie',
    slug: 'under-armour-project-rock-training-hoodie',
    sku: 'UAR-PR-HOODIE',
    categorySlug: 'appliances',
    brandSlug: 'under-armour',
    shortDescription: 'Heavyweight French Terry fleece with 4-way stretch material and Dwayne Johnson Iron Bull insignia.',
    description: 'Project Rock training gear was built to help you find boundaries, then push right through them. Ultra-soft cotton-blend fleece with a brushed interior for extra gym warmth.',
    basePrice: 90,
    salePrice: 79,
    costPrice: 42,
    stockQuantity: 40,
    lowStockThreshold: 10,
    isFeatured: false,
    isNewArrival: false,
    tags: ['under armour', 'project rock', 'hoodie', 'training', 'gym'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=1200&auto=format&fit=crop&q=80', altText: 'Project Rock Hoodie Model', isPrimary: true, displayOrder: 1 },
    ],
    specifications: [
      { group: 'Material', key: 'Blend', value: '80% Cotton / 20% Polyester French Terry' },
      { group: 'Fit', key: 'Cut', value: 'Loose, fuller cut for complete comfort' },
    ],
    hasVariants: true,
    variants: [
      { sku: 'UAR-PR-M', title: 'Pitch Gray / M', price: 90, salePrice: 79, stockQuantity: 20, attributes: { Size: 'M' } },
      { sku: 'UAR-PR-L', title: 'Pitch Gray / L', price: 90, salePrice: 79, stockQuantity: 20, attributes: { Size: 'L' } },
    ],
    seo: {
      metaTitle: 'Under Armour Project Rock Training Hoodie | ZYLO',
      metaDescription: 'Shop Dwayne Johnson\'s Under Armour Project Rock hoodie at ZYLO.',
      keywords: ['under armour project rock', 'gym hoodie', 'training apparel'],
      canonicalUrl: 'https://zylo.com/products/under-armour-project-rock-training-hoodie',
      ogImage: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=1200',
    },
  },
  {
    name: 'GoPro HERO13 Black Action Camera',
    slug: 'gopro-hero13-black-action-camera',
    sku: 'GPR-HERO13-BLK',
    categorySlug: 'cameras',
    brandSlug: 'gopro',
    shortDescription: '5.3K 60fps action camera with HB-Series lens auto-detection, HyperSmooth 6.0, and waterproof to 33ft.',
    description: 'HERO13 Black is the ultimate camera for every creator. In addition to best-in-class 5.3K60 video and legendary ruggedness, it features compatibility with HB-Series Lenses that expand capture capabilities for ultra-wide POVs and macro shots.',
    basePrice: 399,
    salePrice: 379,
    costPrice: 260,
    stockQuantity: 32,
    lowStockThreshold: 6,
    isFeatured: true,
    isNewArrival: true,
    tags: ['gopro', 'hero13 black', 'action camera', 'waterproof', 'hypersmooth', '4k video'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=1200&auto=format&fit=crop&q=80', altText: 'GoPro Camera Mount Angle', isPrimary: true, displayOrder: 1 },
    ],
    specifications: [
      { group: 'Video', key: 'Video Resolution', value: '5.3K 60fps / 4K 120fps / 2.7K 240fps' },
      { group: 'Stabilization', key: 'HyperSmooth', value: 'HyperSmooth 6.0 with 360° Horizon Lock' },
      { group: 'Waterproof', key: 'Depth', value: 'Rugged + Waterproof to 33ft (10m)' },
    ],
    hasVariants: false,
    variants: [],
    seo: {
      metaTitle: 'GoPro HERO13 Black Action Camera | ZYLO Store',
      metaDescription: 'Order the GoPro HERO13 Black with 5.3K video and HyperSmooth 6.0 stabilization.',
      keywords: ['gopro hero13', 'action camera', 'waterproof camera'],
      canonicalUrl: 'https://zylo.com/products/gopro-hero13-black-action-camera',
      ogImage: 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=1200',
    },
  },
  {
    name: 'Leica Q3 Compact Full-Frame Camera',
    slug: 'leica-q3-compact-full-frame-camera',
    sku: 'LCA-Q3-28MM',
    categorySlug: 'cameras',
    brandSlug: 'leica',
    shortDescription: '60MP BSI CMOS full-frame sensor with fixed Summilux 28mm f/1.7 ASPH prime lens and 8K video.',
    description: 'A masterpiece of precision optical craftsmanship made in Germany. The Leica Q3 combines a phenomenal 60MP sensor, classic rangefinder ergonomics, tiltable touchscreen, and legendary Summilux 28mm f/1.7 glass.',
    basePrice: 5995,
    salePrice: null,
    costPrice: 4600,
    stockQuantity: 4,
    lowStockThreshold: 2,
    isFeatured: true,
    isNewArrival: false,
    tags: ['leica', 'leica q3', 'luxury camera', 'german optics', 'summilux', 'full frame'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=1200&auto=format&fit=crop&q=80', altText: 'Leica Camera Top Angle', isPrimary: true, displayOrder: 1 },
    ],
    specifications: [
      { group: 'Sensor', key: 'Sensor', value: '60.3MP Full-Frame BSI CMOS (Triple-Resolution Tech)' },
      { group: 'Lens', key: 'Optical Lens', value: 'Leica Summilux 28mm f/1.7 ASPH with Macro mode' },
      { group: 'Origin', key: 'Manufacturing', value: 'Handcrafted in Wetzlar, Germany' },
    ],
    hasVariants: false,
    variants: [],
    seo: {
      metaTitle: 'Leica Q3 Full-Frame Compact Camera | ZYLO Luxury',
      metaDescription: 'Shop the authentic Leica Q3 camera with Summilux 28mm f/1.7 lens at ZYLO.',
      keywords: ['leica q3', 'leica camera', 'luxury mirrorless'],
      canonicalUrl: 'https://zylo.com/products/leica-q3-compact-full-frame-camera',
      ogImage: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=1200',
    },
  },
  {
    name: 'Nikon Z8 Mirrorless Camera Body',
    slug: 'nikon-z8-mirrorless-camera-body',
    sku: 'NKN-Z8-BODY',
    categorySlug: 'cameras',
    brandSlug: 'nikon',
    shortDescription: 'Flagship Z9 capabilities packed into a 30% smaller body with 45.7MP stacked sensor and 8K 60p RAW.',
    description: 'The ultimate hybrid video and stills workstation. The Nikon Z8 features an all-electronic shutter, 120 fps continuous shooting, subject detection algorithms, and internal 12-bit RAW video recording.',
    basePrice: 3499,
    salePrice: 3299,
    costPrice: 2600,
    stockQuantity: 10,
    lowStockThreshold: 3,
    isFeatured: true,
    isNewArrival: false,
    tags: ['nikon', 'nikon z8', 'camera', 'mirrorless', '8k raw', 'pro camera'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=1200&auto=format&fit=crop&q=80', altText: 'Nikon Z8 Lens Mount View', isPrimary: true, displayOrder: 1 },
    ],
    specifications: [
      { group: 'Sensor', key: 'Sensor', value: '45.7MP Full-Frame Stacked CMOS' },
      { group: 'Video', key: 'Internal RAW', value: '8K 60p N-RAW / 4K 120p ProRes' },
      { group: 'Shutter', key: 'Shutter', value: 'Pure Electronic Shutter up to 1/32000s' },
    ],
    hasVariants: false,
    variants: [],
    seo: {
      metaTitle: 'Nikon Z8 Mirrorless Camera Body | ZYLO Store',
      metaDescription: 'Shop Nikon Z8 full-frame camera with 45.7MP stacked sensor and 8K recording.',
      keywords: ['nikon z8', 'nikon mirrorless', 'hybrid video camera'],
      canonicalUrl: 'https://zylo.com/products/nikon-z8-mirrorless-camera-body',
      ogImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=1200',
    },
  },
  {
    name: 'KitchenAid Artisan 5-Quart Stand Mixer',
    slug: 'kitchenaid-artisan-5-quart-stand-mixer',
    sku: 'KTD-ART5Q-MIXER',
    categorySlug: 'appliances',
    brandSlug: 'kitchenaid',
    shortDescription: 'Iconic tilt-head culinary stand mixer with 10 speeds and 59 touchpoints per rotation for thorough blending.',
    description: 'Whether you need 9 dozen signature cookies or shredded chicken for Taco Tuesday, the KitchenAid Artisan Series 5 Quart Tilt-Head Stand Mixer has the capacity and planetary mixing action for every recipe.',
    basePrice: 449,
    salePrice: 399,
    costPrice: 280,
    stockQuantity: 24,
    lowStockThreshold: 5,
    isFeatured: true,
    isNewArrival: false,
    tags: ['kitchenaid', 'artisan', 'stand mixer', 'baking', 'kitchen', 'appliances'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1594385208974-2e75f8d7bb48?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1594385208974-2e75f8d7bb48?w=1200&auto=format&fit=crop&q=80', altText: 'KitchenAid Red Stand Mixer', isPrimary: true, displayOrder: 1 },
    ],
    specifications: [
      { group: 'Capacity', key: 'Bowl Capacity', value: '5 Quarts (Stainless steel with ergonomic handle)' },
      { group: 'Motor', key: 'Speed Settings', value: '10 speeds with planetary action' },
      { group: 'Attachments', key: 'Included', value: 'Flat beater, dough hook, 6-wire whip, pouring shield' },
    ],
    hasVariants: true,
    variants: [
      { sku: 'KTD-ART5Q-RED', title: 'Empire Red', price: 449, salePrice: 399, stockQuantity: 14, attributes: { Color: 'Empire Red' } },
      { sku: 'KTD-ART5Q-BLK', title: 'Onyx Black', price: 449, salePrice: 399, stockQuantity: 10, attributes: { Color: 'Onyx Black' } },
    ],
    seo: {
      metaTitle: 'KitchenAid Artisan 5-Quart Stand Mixer | ZYLO Store',
      metaDescription: 'Shop genuine KitchenAid Artisan stand mixer with planetary mixing action.',
      keywords: ['kitchenaid mixer', 'artisan 5 quart', 'baking mixer'],
      canonicalUrl: 'https://zylo.com/products/kitchenaid-artisan-5-quart-stand-mixer',
      ogImage: 'https://images.unsplash.com/photo-1594385208974-2e75f8d7bb48?w=1200',
    },
  },
  {
    name: 'Sennheiser Momentum 4 Wireless Headphones',
    slug: 'sennheiser-momentum-4-wireless-headphones',
    sku: 'SNH-MOM4-WIRELESS',
    categorySlug: 'audio',
    brandSlug: 'sennheiser',
    shortDescription: 'Audiophile-inspired 42mm sound transducers with 60-hour battery life and Adaptive Noise Cancellation.',
    description: 'Sennheiser\'s MOMENTUM 4 Wireless sets the standard for wireless sound quality. Enjoy superior musicality with an audiophile-inspired 42mm transducer system and extraordinary 60-hour playtime.',
    basePrice: 379,
    salePrice: 329,
    costPrice: 220,
    stockQuantity: 35,
    lowStockThreshold: 7,
    isFeatured: false,
    isNewArrival: false,
    tags: ['sennheiser', 'momentum 4', 'audiophile', 'wireless headphones', 'anc', '60h battery'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=1200&auto=format&fit=crop&q=80', altText: 'Sennheiser Momentum Headphones Angle', isPrimary: true, displayOrder: 1 },
    ],
    specifications: [
      { group: 'Audio', key: 'Transducer', value: '42mm dynamic speaker driver' },
      { group: 'Battery', key: 'Playtime', value: 'Up to 60 hours with Bluetooth and ANC on' },
      { group: 'Codecs', key: 'Bluetooth Codecs', value: 'aptX Adaptive, aptX, AAC, SBC' },
    ],
    hasVariants: true,
    variants: [
      { sku: 'SNH-MOM4-BLK', title: 'Black', price: 379, salePrice: 329, stockQuantity: 20, attributes: { Color: 'Black' } },
      { sku: 'SNH-MOM4-WHT', title: 'White', price: 379, salePrice: 329, stockQuantity: 15, attributes: { Color: 'White' } },
    ],
    seo: {
      metaTitle: 'Sennheiser Momentum 4 Wireless Headphones | ZYLO',
      metaDescription: 'Shop Sennheiser Momentum 4 wireless headphones with 60-hour battery life.',
      keywords: ['sennheiser momentum 4', 'audiophile headphones', 'wireless anc'],
      canonicalUrl: 'https://zylo.com/products/sennheiser-momentum-4-wireless-headphones',
      ogImage: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=1200',
    },
  },
  {
    name: 'Dell XPS 16 OLED Laptop',
    slug: 'dell-xps-16-oled-laptop',
    sku: 'DLL-XPS16-OLED',
    categorySlug: 'laptops',
    brandSlug: 'dell',
    shortDescription: 'Intel Core Ultra 7 processor with 4K+ OLED InfinityEdge touch display and NVIDIA GeForce RTX 4070.',
    description: 'Iconic minimalism meets extreme creative horsepower. Crafted with CNC machined aluminum and Gorilla Glass 3, featuring touch function rows, seamless glass haptic touchpad, and 4K+ OLED infinity visuals.',
    basePrice: 2499,
    salePrice: 2299,
    costPrice: 1750,
    stockQuantity: 12,
    lowStockThreshold: 3,
    isFeatured: true,
    isNewArrival: true,
    tags: ['dell', 'xps 16', 'oled laptop', 'rtx 4070', 'intel core ultra', 'workstation'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=1200&auto=format&fit=crop&q=80', altText: 'Dell XPS Laptop Open View', isPrimary: true, displayOrder: 1 },
    ],
    specifications: [
      { group: 'Processor', key: 'CPU', value: 'Intel Core Ultra 7 155H (16 cores, NPU AI boost)' },
      { group: 'Display', key: 'Screen', value: '16.3-inch 4K+ (3840 x 2400) OLED Touch InfinityEdge' },
      { group: 'Graphics', key: 'GPU', value: 'NVIDIA GeForce RTX 4070 (8GB GDDR6)' },
    ],
    hasVariants: false,
    variants: [],
    seo: {
      metaTitle: 'Dell XPS 16 OLED Laptop | ZYLO Store',
      metaDescription: 'Shop Dell XPS 16 OLED laptop with Intel Core Ultra and RTX 4070 graphics.',
      keywords: ['dell xps 16', 'dell oled laptop', 'rtx 4070 laptop'],
      canonicalUrl: 'https://zylo.com/products/dell-xps-16-oled-laptop',
      ogImage: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=1200',
    },
  },
  {
    name: 'Asus ROG Zephyrus G16 Gaming Laptop',
    slug: 'asus-rog-zephyrus-g16-gaming-laptop',
    sku: 'ASU-ROG-G16-4080',
    categorySlug: 'laptops',
    brandSlug: 'asus-rog',
    shortDescription: 'Ultra-thin gaming powerhouse with ROG Nebula 2.5K 240Hz OLED display and NVIDIA RTX 4080.',
    description: 'Power, precision, and elegance define the 2024 Zephyrus G16. Thinner and sleeker than ever, featuring an all-aluminum CNC chassis with Slash Lighting on the lid, paired with an ultra-responsive 0.2ms OLED panel.',
    basePrice: 2899,
    salePrice: 2699,
    costPrice: 2100,
    stockQuantity: 11,
    lowStockThreshold: 3,
    isFeatured: true,
    isNewArrival: false,
    tags: ['asus rog', 'zephyrus g16', 'gaming laptop', 'rtx 4080', 'oled 240hz'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=1200&auto=format&fit=crop&q=80', altText: 'ROG Gaming Laptop Dark View', isPrimary: true, displayOrder: 1 },
    ],
    specifications: [
      { group: 'Performance', key: 'GPU', value: 'NVIDIA GeForce RTX 4080 (12GB GDDR6)' },
      { group: 'Display', key: 'OLED', value: '16-inch 2.5K 240Hz 0.2ms ROG Nebula OLED' },
      { group: 'Weight', key: 'Chassis', value: '1.85 kg CNC-milled aluminum' },
    ],
    hasVariants: false,
    variants: [],
    seo: {
      metaTitle: 'Asus ROG Zephyrus G16 Gaming Laptop | ZYLO Store',
      metaDescription: 'Shop Asus ROG Zephyrus G16 with RTX 4080 and 240Hz OLED display.',
      keywords: ['asus rog zephyrus g16', 'rtx 4080 gaming laptop', 'rog nebula oled'],
      canonicalUrl: 'https://zylo.com/products/asus-rog-zephyrus-g16-gaming-laptop',
      ogImage: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=1200',
    },
  },
  {
    name: 'LG C4 65" 4K OLED evo Smart TV',
    slug: 'lg-c4-65-4k-oled-evo-smart-tv',
    sku: 'LGE-OLED65C4',
    categorySlug: 'appliances',
    brandSlug: 'lg',
    shortDescription: 'Self-lit OLED evo pixels with Brightness Booster, α9 AI Processor Gen7, and 144Hz VRR gaming support.',
    description: 'LG OLED evo delivers infinite contrast, 100% color fidelity, and 0.1ms response times. Enhanced by the α9 AI Processor Gen7 for lifelike detail and Brightness Booster for luminous highlights.',
    basePrice: 2299,
    salePrice: 1999,
    costPrice: 1550,
    stockQuantity: 14,
    lowStockThreshold: 4,
    isFeatured: true,
    isNewArrival: false,
    tags: ['lg', 'oled evo', 'lg c4', '4k tv', 'smart tv', '144hz', 'gaming tv'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1461151304267-38535e780c79?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1461151304267-38535e780c79?w=1200&auto=format&fit=crop&q=80', altText: 'LG OLED TV Screen Cinematic View', isPrimary: true, displayOrder: 1 },
    ],
    specifications: [
      { group: 'Display', key: 'Display Technology', value: '4K Self-Lighting OLED evo' },
      { group: 'Processor', key: 'AI Engine', value: 'α9 AI Processor Gen7' },
      { group: 'Gaming', key: 'Gaming Features', value: '144Hz, G-Sync, FreeSync Premium, 4x HDMI 2.1' },
    ],
    hasVariants: false,
    variants: [],
    seo: {
      metaTitle: 'LG C4 65" 4K OLED evo Smart TV | ZYLO Store',
      metaDescription: 'Shop LG C4 65-inch OLED evo TV with 144Hz refresh rate and α9 AI processor.',
      keywords: ['lg c4 oled', '65 inch oled tv', 'lg smart tv'],
      canonicalUrl: 'https://zylo.com/products/lg-c4-65-4k-oled-evo-smart-tv',
      ogImage: 'https://images.unsplash.com/photo-1461151304267-38535e780c79?w=1200',
    },
  },
  {
    name: 'Lego Technic Ferrari Daytona SP3',
    slug: 'lego-technic-ferrari-daytona-sp3',
    sku: 'LGO-TEC-42143',
    categorySlug: 'gaming',
    brandSlug: 'lego',
    shortDescription: '1:8 scale supercar model with 3,778 pieces, working V12 engine, and 8-speed sequential paddle gearbox.',
    description: 'Enter a zone of pure mindfulness with the LEGO Technic Ferrari Daytona SP3. Classic red styling, chrome-painted rims, butterfly doors, and removable roof recreate the iconic Italian supercar.',
    basePrice: 449,
    salePrice: 419,
    costPrice: 290,
    stockQuantity: 19,
    lowStockThreshold: 4,
    isFeatured: false,
    isNewArrival: false,
    tags: ['lego', 'lego technic', 'ferrari', 'supercar', 'daytona sp3', 'collector'],
    thumbnailUrl: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=800&auto=format&fit=crop&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=1200&auto=format&fit=crop&q=80', altText: 'Lego Technic Supercar Build Angle', isPrimary: true, displayOrder: 1 },
    ],
    specifications: [
      { group: 'Details', key: 'Piece Count', value: '3,778 pieces' },
      { group: 'Scale', key: 'Scale Ratio', value: '1:8 scale (Over 59cm long, 25cm wide)' },
      { group: 'Gearbox', key: 'Transmission', value: 'Working 8-speed sequential gearbox with paddle shifters' },
    ],
    hasVariants: false,
    variants: [],
    seo: {
      metaTitle: 'LEGO Technic Ferrari Daytona SP3 42143 | ZYLO',
      metaDescription: 'Build the 1:8 scale LEGO Technic Ferrari Daytona SP3 with working V12 engine.',
      keywords: ['lego ferrari', 'technic 42143', 'ferrari daytona sp3 lego'],
      canonicalUrl: 'https://zylo.com/products/lego-technic-ferrari-daytona-sp3',
      ogImage: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=1200',
    },
  },
];

@Injectable()
export class ProductsSeedService implements OnModuleInit {
  private readonly logger = new Logger(ProductsSeedService.name);

  constructor(
    @InjectModel(Product.name) private readonly productModel: Model<ProductDocument>,
    @InjectModel(Brand.name) private readonly brandModel: Model<BrandDocument>,
    @InjectModel(Category.name) private readonly categoryModel: Model<CategoryDocument>,
  ) {}

  async onModuleInit() {
    try {
      await this.seed();
    } catch (err: any) {
      this.logger.error(`Error during products auto-seed: ${err?.message}`, err?.stack);
    }
  }

  async seed(): Promise<{ seeded: number; existing: number }> {
    const count = await this.productModel.countDocuments();
    this.logger.log(`Checking products collection (current count: ${count})...`);
    let seeded = 0;

    // Cache categories & brands
    const [allCategories, allBrands] = await Promise.all([
      this.categoryModel.find().lean().exec(),
      this.brandModel.find().lean().exec(),
    ]);

    const categoryMap = new Map<string, Types.ObjectId>();
    for (const cat of allCategories) {
      categoryMap.set(cat.slug, cat._id as Types.ObjectId);
    }

    const brandMap = new Map<string, { id: Types.ObjectId; name: string }>();
    for (const b of allBrands) {
      brandMap.set(b.slug, { id: b._id as Types.ObjectId, name: b.name });
    }

    // Default fallback category if specific slug is missing
    const defaultCategoryId = allCategories[0]?._id as Types.ObjectId;
    const defaultBrand = allBrands[0] ? { id: allBrands[0]._id as Types.ObjectId, name: allBrands[0].name } : null;

    for (const item of SEED_PRODUCTS) {
      const categoryId = categoryMap.get(item.categorySlug) || defaultCategoryId;
      const brand = brandMap.get(item.brandSlug) || defaultBrand;

      if (!categoryId || !brand) {
        this.logger.warn(`Skipping seed product "${item.name}": category or brand missing.`);
        continue;
      }

      const existing = await this.productModel.exists({ slug: item.slug });
      if (existing) {
        continue;
      }

      await this.productModel.create({
        name: item.name,
        slug: item.slug,
        sku: item.sku,
        shortDescription: item.shortDescription,
        description: item.description,
        categoryId,
        brandId: brand.id,
        basePrice: item.basePrice,
        salePrice: item.salePrice || null,
        costPrice: item.costPrice || null,
        stockQuantity: item.stockQuantity,
        lowStockThreshold: item.lowStockThreshold || 5,
        trackInventory: true,
        allowBackorders: false,
        status: 'PUBLISHED',
        isFeatured: item.isFeatured || false,
        isNewArrival: item.isNewArrival || false,
        tags: item.tags,
        thumbnailUrl: item.thumbnailUrl,
        images: item.images,
        specifications: item.specifications,
        hasVariants: item.hasVariants || false,
        variants: item.variants || [],
        seo: item.seo,
      });

      // Increment brand productCount
      await this.brandModel.findByIdAndUpdate(brand.id, { $inc: { productCount: 1 } });
      seeded++;
    }

    this.logger.log(`Successfully seeded ${seeded} premier catalog products.`);
    return { seeded, existing: 0 };
  }
}
